libgraviton/graviton

phpunit.xml.dist
src/Graviton/SecurityBundle/Tests/User/AirlockAuthenticationKeyUserProviderTest.php

This deactivates processIsolation again and makes everything run on travis as before.

fix the egging around of phpunit on travis

---

composer.json
composer.lock

as said.. rql is completely broken if we don't fix it now; also in the wrappers it's broken now..

fix rql parser dep; we need to integrate 1.* now

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/ProductControllerTest.php
src/Graviton/EntityBundle/Tests/Controller/CountryControllerTest.php
src/Graviton/I18nBundle/Tests/Controller/LanguageControllerTest.php
src/Graviton/SchemaBundle/Document/Schema.php

this way, swagger will display them under the model..

as discussed, let's remove translatables from schema document.. 

---

app/config/parameters.yml
app/config/parameters.yml.dist
src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php
src/Graviton/GeneratorBundle/Generator/DynamicBundleBundleGenerator.php

read param (normally empty) and incorporate class names from there as additional bundles into dynamic bundlebundle

simple ability to add more bundles to dynamic bundlebundle via parameter..

---

app/config/config_test.yml

don't fix path to FrameWorkBundle as it won't find it in wrapper context..., use flexible syntax..

fix path location to test.xml

---

src/Graviton/CoreBundle/DataFixtures/MongoDB/LoadAppData.php
src/Graviton/CoreBundle/Document/App.php
src/Graviton/CoreBundle/Resources/config/doctrine/App.mongodb.xml
src/Graviton/CoreBundle/Resources/config/schema/App.json
src/Graviton/CoreBundle/Resources/config/serializer/Document.App.xml
src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php

* add 'order' field to /core/app
* add new fixture for app 'tablet' - this is the one the /configuration/module fixtures will point to
* changed tests to reflect changes..

add field 'order' to /core/app

---

composer.json
dev-cleanstart.sh
src/Graviton/GeneratorBundle/Command/CleanDynamicBundleCacheCommand.php
src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php
src/Graviton/GeneratorBundle/Composer/ScriptHandler.php
src/Graviton/GeneratorBundle/Resources/config/services.xml
src/Graviton/GeneratorBundle/Tests/Command/CleanDynamicBundleCacheCommandTest.php

* Make symfony command to clean GravitonDyn
* Wrap our 2 commands in a composer ScriptHandler
* Integrate that into composer.json
* Remove that from dev-cleanstart.sh

generator composer integration

---

src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php
src/Graviton/GeneratorBundle/Resources/config/services.xml

discovered this upon installing it with different config..

take collection name from parameters.. fixes #69

---

CHANGELOG.md
composer.json
composer.lock

***Do not merge on github!!!!***
We need to start issuing regular releases again. This one is awfully large and thus not really handy to document.
To merge this you should do a local checkout of the branch and then ``git flow release finish`` it.
Since this is the first release I'm doing it as a PR. This is so we can discuss it and how we would like to do releases going further.
~~I propose the following:~~
* ~~we start the ``releases/<next>`` branch early~~
* ~~we then just add to its changelog during the sprint without merging or rebasing anything on the release branch~~
* ~~at release time the branch gets squashed and finished using ``git flow``~~
* ~~we then use a pr like this one for voting on finalizing a release (using :+1: and :-1:)~~
* ~~this pr is created and closed before our …

Release v0.7.0

---

.travis.yml

The reformatting was done by the travis cli so I'm leaving it in.
Maybe @paza want to merge this himself as he is the one whos to blame for it ;)

travis encrypt --add for notifications.hipchat.rooms

---

src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
src/Graviton/GeneratorBundle/Resources/skeleton/validator/validation.xml.twig

before you could POST 'true' and 'false' (booleans) and it would save it as int's (0 and 1). this is not a sane behavior.. add tests for module to test this..

generate validation rules for int & float fields

---

src/Graviton/I18nBundle/Resources/config/validation.xml

this enables us to insert valid translatables again..

add id not blank constraint to Translatable

---

src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.php.twig

i need this in a service bundle in order to generate objects from different objects and return objects that have an id property..

add setter for id property in generated documents

---

.travis.yml
composer.lock
src/Graviton/BundleBundle/Tests/GravitonBundleBundleTest.php
src/Graviton/ExceptionBundle/Listener/RestExceptionListener.php
src/Graviton/GeneratorBundle/Command/GenerateBundleCommand.php
src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php
src/Graviton/GeneratorBundle/Composer/ScriptHandler.php
src/Graviton/GeneratorBundle/Definition/JsonDefinition.php
src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
src/Graviton/GeneratorBundle/Tests/Generator/ResourceGeneratorTest.php
src/Graviton/RestBundle/Listener/JsonRequestListener.php
src/Graviton/RestBundle/Listener/ValidationRequestListener.php
src/Graviton/RestBundle/Subscriber/RestEventSubscriber.php
src/Graviton/SecurityBundle/Tests/Authentication/Strategies/CookieFieldStrategyTest.php
src/Graviton/SecurityBundle/Tests/Authentication/Strategies/HeaderFieldStrategyTest.php
src/Graviton/SecurityBundle/Tests/User/AirlockAuthenticationKeyUserProviderTest.php
src/Graviton/SecurityBundle/Voter/OwnContextVoter.php
src/Graviton/SwaggerBundle/Composer/ScriptHandler.php
src/Graviton/SwaggerBundle/Service/Swagger.php

These are all really small. Basically I just fixed a heap of scrutinizer issues to get some distance to the whole ref thing for a change.
I also ran a ``composer update`` just for the heck of it and pulled in various small changes there as well.
The most important change is probably in f5c3be8 and I'll split that out if we can't get this merged ASAP.

Small fixes throughout

---

app/AppKernel.php
composer.json
composer.lock

|      |      |
|-----|-----|
| ![shaky_waffle](https://cloud.githubusercontent.com/assets/116588/7360075/d993a276-ed46-11e4-84c8-f63fd95e63ed.gif) | ![waffle-doge](https://cloud.githubusercontent.com/assets/116588/7359996/f00ce2fc-ed45-11e4-9f30-aa602c1ad0b3.png) |
We all need waffles, we'll be using them to store stuff in S3 buckets as well as for test isolation purposes.
There are probably less delicious bundles that could help us here & I'm probably only proposing this one so fast because I'm being silly. My gut feelings are ok with it as well though.

Add KnpGaufretteBundle

---

src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php

Thes removes the sillyness that was loading definitions from mongodb during build time. I simply introdued way to much side effects during install.
The Defs that where loaded this was are now directly in a git repo where we have control of when and how they change and we always know which version was used at the time.
The new grv/evoja-loadconfig-bundle has more info on how to use them and how to update the defs in the bundle. Talk to me if you need more info or a pointer to our internal repo.
Since this decouples our build process from injected loadconfigs via mongo it will make automated deploys of loadconfig based wrappers possible.

Don't load JsonDefs from Mongo

---

src/Graviton/CoreBundle/Resources/definition/Config.json

Finishes the work @lapistano did on #101. It also adds some meaningful fixtures that look like the kind of data we would like in this service.

finish /core/config service

---

composer.json
composer.lock

> OK GitHub... Please bump all composer deps.
* contains rql-parser-bundle 0.2.0
* stabilizes some deps where possible

bump dependencies (3rd party and rql-parser-bundle)

---

composer.json
composer.lock

Contains a ``/person/customer`` service that will come in handy for our work on writable customers.

Add graviton/test-services-bundle to require-dev

---

src/Graviton/GeneratorBundle/Command/GenerateResourceCommand.php
src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
src/Graviton/GeneratorBundle/Resources/config/services.xml

This configures ``GenerateResourceCommand`` as a service through the DIC.

ResourceGenerator as a service

---

src/Graviton/GeneratorBundle/Command/GenerateResourceCommand.php
src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php

Gets rid of ResourceGenerators InputInterface dependency and cleans up some type-hinting.

Untangle input dependency

---

src/Graviton/CoreBundle/Controller/MainController.php
src/Graviton/CoreBundle/Tests/Controller/MainControllerTest.php
src/Graviton/RestBundle/Service/RestUtils.php
src/Graviton/RestBundle/Service/RestUtilsInterface.php

I made RestUtils final in #123 thus introducing breakage in #112. This is now being fixed by adding the ``RestUtilsInterface`` and coding against it.

Make RestUtils testable again by adding an interface

---

src/Graviton/RestBundle/Subscriber/RestEventSubscriber.php
src/Graviton/SecurityBundle/Listener/AuthenticationLogger.php
src/Graviton/SecurityBundle/Tests/Listener/AuthenticationLoggerTest.php

making the way towards oauth; those two classes made some problems as they expect things that are not always there as they think.. this PR tries to fix that.

fix two classes that expect things that are not always there ;-)

---

web/app.php

Activate ``AppCache`` in non ``dev`` cases.

Add AppCache for non debug cases

---

src/Graviton/GeneratorBundle/Definition/Loader/Strategy/DirStrategy.php
src/Graviton/GeneratorBundle/Definition/Loader/Strategy/DirStrategyInterface.php
src/Graviton/GeneratorBundle/Definition/Loader/Strategy/ScanStrategy.php

Expose DirStrategy as proper interface

---

web/app_dev.php

fix issue pointing to not existing app_env ;-/

---

composer.json
composer.lock
src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/PersonBundle/Controller/AbstractCustomerController.php
src/Graviton/RestBundle/Controller/RestController.php
src/Graviton/RestBundle/Routing/Loader/ActionUtils.php
src/Graviton/RestBundle/Routing/Loader/BasicLoader.php
src/Graviton/SwaggerBundle/Service/Swagger.php
src/Graviton/TestBundle/Client.php

This was broken and posed to become an issue anyhow.

Stop supporting PATCH verb

---

app/config/config_airlock_prod.yml
app/config/security_airlock.yml
app/config/security_prod.yml
manifest.yml
src/Graviton/SecurityBundle/Voter/ServiceAllowedVoter.php

This doesn't add any auth on cf deploys yet. It makes us use proper caching so everything is very much faster.

Fix prod env and switch cf to it

---

composer.json
composer.lock
src/Graviton/RestBundle/Model/DocumentModel.php

Bump rql-parser-bundle and rql-parser

---

.bp-config/nginx/server-locations.conf
.docker-config/nginx/defaults.conf

disable nginx client_max_body_size for cloud pushes..

---

composer.json
composer.lock

Also updates ``jms/serializer`` to ``1.0.0`` :eyes:

Update all deps (specially rql-parser-bundle)

---

src/Graviton/FileBundle/Controller/FileController.php
src/Graviton/FileBundle/Resources/definition/File.json
src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php

* Now it's possible to update the content of a existing file.
* Implement new metadata (link.type and filename)

extend put action of file service

---

src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php

introduced by merging both #160 and #162...

Fix failing test for NotBlank contraint on filename

---

composer.json
composer.lock

After this we can make jenkins configure deploy-scripts in an empty workspace with ``composer configure``.

Introduce composer configure command for jenkins

---

src/Graviton/DocumentBundle/Form/Type/DocumentType.php

Make date and datetime fields validate properly...

Generate date and datetime fields properly

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/ProductControllerTest.php
src/Graviton/EntityBundle/Tests/Controller/CountryControllerTest.php
src/Graviton/I18nBundle/Tests/Controller/LanguageControllerTest.php
src/Graviton/I18nBundle/Tests/Controller/TranslatableControllerTest.php
src/Graviton/RestBundle/Controller/RestController.php
src/Graviton/RestBundle/Routing/Loader/ActionUtils.php
src/Graviton/RestBundle/Routing/Loader/BasicLoader.php

tahdah! This should fix [GRV-1915](https://issue.swisscom.ch/browse/GRV-1915).

Don't return body in OPTIONS requests

---

src/Graviton/RestBundle/Model/DocumentModel.php

Contains the work from #182 as well as an additional change that makes us only sort if we need to.

Fix sorting

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/ExceptionBundle/Listener/RqlSyntaxErrorListener.php
src/Graviton/ExceptionBundle/Resources/config/services.xml

So our clients get told what they did wrong.

Better RQL error messages

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/RestBundle/Controller/RestController.php

PUT now returns 204 (which is actually more precise than 200 *g)

change return codes

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
src/Graviton/I18nBundle/Tests/Controller/LanguageControllerTest.php
src/Graviton/RestBundle/Controller/RestController.php

as discussed; PUT has no Location header anymore..

no location on put

---

src/Graviton/RestBundle/Validator/Constraints/ReadOnly/ReadOnlyValidator.php

I'll add some tests for this (for all readOnlys) in #125 once this is merged..

properly compare datetimes so they can also be readOnly..

---

src/Graviton/FileBundle/Resources/definition/File.json

don't require the metadata field 'filename' in file..

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
src/Graviton/ExceptionBundle/Listener/ValidationExceptionListener.php
src/Graviton/FileBundle/Controller/FileController.php
src/Graviton/FileBundle/Resources/definition/File.json
src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php

add file mtime

---

src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
src/Graviton/CoreBundle/Tests/resources/showcase-rql-select-filtred.json
src/Graviton/CoreBundle/Tests/resources/showcase-rql-select-initial.json
src/Graviton/RestBundle/Listener/RqlSelectResponseListener.php
src/Graviton/RestBundle/Resources/config/services.xml
src/Graviton/RestBundle/Tests/Listener/RqlSelectResponseListenerTest.php
src/Graviton/RestBundle/Tests/Utils/ObjectSlicerTest.php
src/Graviton/RestBundle/Utils/ObjectSlicer.php

I tried to use `select` in MongoDb query but it cannot be applied to references and throws exceptions if invalid fields is specified.
Also I tried to implement `ExclusionStrategy` for `Serializer` but it cannot be applied to `schemaless` (`hash` or `array`) fields.
Then I implemented  `ResponseListener` that filters JSON using `ObjectSlicer`

2058 rql select

---

composer.json
composer.lock
phpunit.xml.dist
src/Graviton/CoreBundle/Resources/config/services.xml
src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
src/Graviton/I18nBundle/Resources/config/services.xml
src/Graviton/PersonBundle/Resources/config/services.xml
src/Graviton/RestBundle/Model/DocumentModel.php

Bump the parser to the next version and clean up encoding of ``(`` and ``)`` where it was part of the query.

RQL parser updates

---

src/Graviton/CoreBundle/Resources/definition/Config.json
src/Graviton/FileBundle/Resources/definition/File.json
src/Graviton/GeneratorBundle/Definition/JsonDefinitionField.php
src/Graviton/GeneratorBundle/Definition/Schema/Field.php
src/Graviton/GeneratorBundle/Resources/config/serializer/Definition.Schema.Field.xml
src/Graviton/GeneratorBundle/Resources/skeleton/model/schema.json.twig
src/Graviton/GeneratorBundle/Tests/Definition/DefinitionElementTest.php
src/Graviton/SchemaBundle/Document/Schema.php
src/Graviton/SchemaBundle/Model/SchemaModel.php
src/Graviton/SchemaBundle/Resources/config/schema/SchemaModel.json
src/Graviton/SchemaBundle/Resources/config/serializer/Document.Schema.xml
src/Graviton/SchemaBundle/Resources/config/services.xml
src/Graviton/SchemaBundle/SchemaUtils.php

I extend the schema with a new attribute named x-collection for ref fields.
With this new attribute a client now, to which collection(end point) a ref field refer.

extend schema information 

---

src/Graviton/CoreBundle/Resources/definition/Module.json

There's another pull request on git.swisscom.com which relates to this one.

added fix id for testing purposes

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/ExceptionBundle/Listener/MalformedInputExceptionListener.php
src/Graviton/ExceptionBundle/Resources/config/services.xml

GRV-2083 useful error message, when posted JSON is malformed

---

composer.json
composer.lock

This bumps our symfony dep to version that was not EOLed more than a week ago...

Can haz symfony 2.7

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/DocumentBundle/Service/ExtReferenceConverter.php
src/Graviton/DocumentBundle/Service/ExtReferenceConverterInterface.php
src/Graviton/DocumentBundle/Tests/Service/ExtReferenceConverterTest.php
src/Graviton/RestBundle/Controller/RestController.php
src/Graviton/RestBundle/Validator/Constraints/ExtReference/ExtReferenceValidator.php

20150721 php7 support

---

src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php

Fix PHP error.

---

src/Graviton/SchemaBundle/Resources/config/schema/SchemaModel.json
src/Graviton/SwaggerBundle/Service/Swagger.php

Cleanup schema info in swagger

---

src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
src/Graviton/DocumentBundle/Listener/ExtReferenceListener.php
src/Graviton/DocumentBundle/Listener/ExtReferenceSearchListener.php
src/Graviton/DocumentBundle/Service/ExtReferenceConverter.php
src/Graviton/DocumentBundle/Service/ExtReferenceConverterInterface.php
src/Graviton/DocumentBundle/Tests/Service/ExtReferenceConverterTest.php
src/Graviton/DocumentBundle/Tests/Types/ExtReferenceTest.php
src/Graviton/DocumentBundle/Types/ExtReference.php
src/Graviton/RestBundle/Tests/Validator/ExtReference/ExtReferenceValidatorTest.php
src/Graviton/RestBundle/Validator/Constraints/ExtReference/ExtReferenceValidator.php

* Fix compatibility with PHP7
* Fix possible errors in `ExtReferenceSearchListener`
* Fix searching by `extref`

20150821 fix php7

---

phpunit.xml.dist
src/Graviton/GeneratorBundle/Tests/Definition/JsonDefinitionFieldTest.php

* Fix unit tests after merging #223 and #220
* Set `memory_limit` in `phpunit.xml.dist`

20150824 fix unit tests

---

composer.lock

Just to make sure we didn't introduce any side-effects lately...

Bump our deps

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
src/Graviton/RestBundle/Controller/RestController.php

This was just doing something random previously. After this DELETE responses are much more inline with what it's contents used to be.

Return 204 and no data on DELETE response

---

composer.lock
src/Graviton/CoreBundle/Tests/Controller/EmptyObjectControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/NullExtrefControllerTest.php

Please merge https://github.com/libgraviton/GravitonTestServicesBundle/pull/15 first

Update test route names.

---

src/Graviton/FileBundle/README.md

Updated README with information about how to configure the bundle and pointed to stepping stones.

Added configuration section

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/SchemaBundle/SchemaUtils.php

https://issue.swisscom.ch/browse/EVO-711

added 'en' as required and added a new assertion

---

app/Resources/views/base.json.twig

Remove trailing whitespaces in JSON response.

---

src/Graviton/FileBundle/Controller/FileController.php
src/Graviton/FileBundle/FileDocumentFactory.php
src/Graviton/FileBundle/FileManager.php
src/Graviton/FileBundle/README.md
src/Graviton/FileBundle/Resources/config/services.xml
src/Graviton/FileBundle/Tests/FileManagerTest.php
src/Graviton/FileBundle/Tests/Fixtures/test.txt
src/Graviton/RestBundle/Tests/Listener/SpecialMimetypeRequestListenerTest.php

Introduces the ability to upload a file and its' meta data in one go.

EVO-771 multipart form data

---

src/Graviton/CoreBundle/Resources/config/schema/App.json
src/Graviton/CoreBundle/Resources/config/schema/Product.json
src/Graviton/CoreBundle/Resources/config/schema/Version.json
src/Graviton/CoreBundle/Tests/Controller/VersionControllerTest.php
src/Graviton/FileBundle/Resources/definition/File.json
src/Graviton/GeneratorBundle/Definition/JsonDefinition.php
src/Graviton/GeneratorBundle/Definition/JsonDefinitionHash.php
src/Graviton/GeneratorBundle/Definition/Schema/Definition.php
src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
src/Graviton/GeneratorBundle/Resources/config/serializer/Definition.Schema.Definition.xml
src/Graviton/GeneratorBundle/Resources/skeleton/model/schema.json.twig
src/Graviton/I18nBundle/Resources/config/schema/Language.json
src/Graviton/I18nBundle/Resources/config/schema/Translatable.json
src/Graviton/I18nBundle/Resources/config/schema/TranslatableLanguage.json
src/Graviton/PersonBundle/Resources/config/schema/PersonContact.json
src/Graviton/SchemaBundle/Model/SchemaModel.php
src/Graviton/SchemaBundle/Resources/config/schema/SchemaModel.json
src/Graviton/SchemaBundle/SchemaUtils.php

This is a rebase of #307 which for some reason was based of off a weird tag of master.

Add schema title support and add titles.

---

app/config/deploy.yml.dist
src/Graviton/DocumentBundle/DependencyInjection/GravitonDocumentExtension.php
src/Graviton/FileBundle/DependencyInjection/GravitonFileExtension.php
src/Graviton/RabbitMqBundle/DependencyInjection/GravitonRabbitMqExtension.php

small changes to graviton finds its VCAP services again..

change to new cloud

---

composer.json
composer.lock

should be the new cloud, not the old ;-)

update the url to our cloud based repo

---

composer.lock

let's bump everything, some useful stuff in there..

bump all deps..

---

app/AppKernel.php
app/config/config.yml
composer.json
composer.lock
src/Graviton/CoreBundle/GravitonCoreBundle.php
src/Graviton/MigrationBundle/Command/MongodbMigrateCommand.php
src/Graviton/MigrationBundle/DependencyInjection/GravitonMigrationExtension.php
src/Graviton/MigrationBundle/GravitonMigrationBundle.php
src/Graviton/MigrationBundle/Resources/config/config.xml
src/Graviton/MigrationBundle/Resources/config/services.xml

Install the mongodb migrations tooling, it's bundle and add a new bundle that contains
a command for running migrations with multiple configurations.

Install antimattr/mongodb-migrations and add wrapper

---

README.md
src/Graviton/FileBundle/README.md
src/Graviton/I18nBundle/README.md

Link to Docs

---

composer.lock

i'm mainly after `graviton/json-schema`, but let's update all our deps..

bump all deps

---

src/Graviton/FileBundle/FileDocumentFactory.php
src/Graviton/FileBundle/FileManager.php
src/Graviton/FileBundle/Resources/definition/File.json
src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
src/Graviton/GeneratorBundle/Definition/JsonDefinitionArray.php
src/Graviton/GeneratorBundle/Tests/Definition/JsonDefinitionArrayTest.php
src/Graviton/GeneratorBundle/Tests/Definition/Loader/Strategy/JsonStrategyTest.php

This PR adds the `additionalInformation` field to the file service.

EVO-763: Add additionalInformation field to file service

---

src/Graviton/ProxyBundle/Definition/Loader/DispersalStrategy/SwaggerStrategy.php
src/Graviton/ProxyBundle/Tests/Definition/Loader/DispersalStrategy/SwaggerStrategyTest.php

fix nasty infinite loop caused by a schema we use. caused by A -> B -> A relations in schema

fix infinite loop

---

composer.lock
src/Graviton/CoreBundle/Tests/resources/showcase-complete.json

fixes our test and bumps to latest testbundle.. required also for #361

fix ShowCaseController test

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/RestBundle/Model/DocumentModel.php

Fix sql error if attempt to query with 0 limit

Zero or Negative limit Exception

---

.travis.yml
composer.json
composer.lock
src/Graviton/I18nBundle/Tests/Form/Type/TranslatableTypeTest.php

I needed to change on test since it symfony seems to have introduced some changes.
I did some digging but couldn't find the actual changes. Tests say everything is fine though.

Update all the things

---

src/Graviton/SecurityBundle/Resources/config/routing.xml
src/Graviton/SecurityBundle/Tests/Controller/WhoAmIControllerTest.php

removed trailing slash from route

Removed faulty trailing slash at service://person/whoami

---

src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php

CONFIGURATION_PARAMETER_CORE_ID

Renaming of Auth Value, data to be sent to queue:

---

app/config/config_test.yml
src/Graviton/CoreBundle/Listener/JsonExceptionListener.php
src/Graviton/CoreBundle/Resources/config/services.xml
src/Graviton/CoreBundle/Tests/Services/JsonExceptionListerTest.php
src/Graviton/CoreBundle/Tests/Services/ReadOnlyServiceTest.php
src/Graviton/I18nBundle/Listener/I18nSerializationListener.php
src/Graviton/RestBundle/Service/RestUtils.php

Only if status code is not 0 .

Exception Lister to return json response.

---

app/config/parameters.yml.dist
src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php
src/Graviton/RabbitMqBundle/Resources/config/services.xml
src/Graviton/RabbitMqBundle/Tests/Listener/EventStatusLinkResponseListenerTest.php

Reverting all the apialias-stuff cause there is a better solution for the workers in sight!

EVO-4790 reverting all the apialias-stuff

---

src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
src/Graviton/DocumentBundle/Form/Type/DocumentType.php
src/Graviton/DocumentBundle/Tests/Form/Type/DocumentTypeTest.php

Return extra fields in error output

---

composer.json
composer.lock

I didn't do a full analysis to check if we are affected somewhere, better safe than sorry.
Feel free to check if you want to: http://symfony.com/blog/cve-2016-4423-large-username-storage-in-session

Bump symfony for CVE-2016-4423

---

src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig

In generator, on building XML definition for MongoDB use single field indexes

Set index as Single Field Indexes

---

src/Graviton/DocumentBundle/Service/ExtReferenceConverter.php

I cherry picked this from @narcoticfresh's branch `feature/other-validation` since I want it ASAP :)

cache route resolving; saves a lot..

---

.travis.yml

if you check https://travis-ci.org/libgraviton/graviton/builds/142129543, it seems to be a bit quicker.. so let's put it there ;-)

try to disable xdebug when not needed on travis

---

composer.lock

We want this bump because of the long int issue that was fixed in xiag/rql-parser@v1.0.2.

Bump rql parser

---

src/Graviton/SchemaBundle/Constraint/IncrementalDateFieldConstraint.php
src/Graviton/SchemaBundle/Resources/config/services.xml
src/Graviton/SchemaBundle/Tests/Controller/IncrementalDateFieldConstraintTest.php

**DO NOT MERGE until #430 has landed in develop**
this was branched off `feature/other-validation` (#430) - as soon that has been merged into develop, the diff will be veeeeery small ;-)
It implements a validator that denies if a given Datetime posted is smaller then the currently saved one - see EVO-4972.
the stuff for this PR is in 3eef270

EVO-4972 - Incremental date fields

---

src/Graviton/RestBundle/Model/DocumentModel.php

should check for repository existence

fix wrong access if repository is not defined

---

src/Graviton/CoreBundle/Composer/ScriptHandler.php
src/Graviton/CoreBundle/Composer/ScriptHandlerBase.php
src/Graviton/GeneratorBundle/Composer/ScriptHandler.php
src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php
src/Graviton/RabbitMqBundle/Resources/config/services.xml
src/Graviton/RabbitMqBundle/Resources/definition/EventStatus.json
src/Graviton/RabbitMqBundle/Tests/Listener/EventStatusLinkResponseListenerTest.php
src/Graviton/SwaggerBundle/Composer/ScriptHandler.php

Feature Add username to event status

---

composer.lock

update jsonpatch library

---

src/Graviton/SchemaBundle/Constraint/Builder/DecimalConstraintBuilder.php

allow more precision on decimal validation..

doesn't hurt, had some data with more precision..

---

composer.json
composer.lock

I put the dependency in composer.json explicitly so all downstreams will be forced to grab it.

Bump guzzle to get httpoxy fixes

---

src/Graviton/RabbitMqBundle/Resources/definition/EventStatus.json
src/Graviton/RabbitMqBundle/Resources/definition/EventStatusAction.json
src/Graviton/RabbitMqBundle/Resources/definition/EventWorker.json
src/Graviton/RabbitMqBundle/Resources/definition/EventWorkerAction.json
src/Graviton/RabbitMqBundle/Tests/Controller/EventStatusControllerTest.php

Adding the reference to the a translated description of the Event Status, new api /event/action.

EVO-5174 Event Worker Action

---

.travis.yml

Composer was looking at all the branches of mongofill to solve the requirement. Only solving for master makes the RAM usage 📉.
I'll be like 💃 when we can get rid of mongofill.

Fix da build (php7 on travis)

---

src/Graviton/RestBundle/Model/DocumentModel.php

We didn't consider people searches with name "space" surname. Tests will follow.

Fix search with space

---

src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
src/Graviton/RestBundle/Model/DocumentModel.php

Same as #462 but against develop since that was merged.

Add simple integration tests that exercises the dotted search feature

---

composer.json
composer.lock

These downgrade combat various issues we caught way too late.

Downgrade symfony and jms/serializer

---

src/Graviton/RestBundle/Controller/RestController.php
src/Graviton/RestBundle/Model/DocumentModel.php

making these changes, on rendering 10 consultations, we save around 10% execution time (it's still very slow, but well) and about 30% of RAM consumption (this mostly by removing the Schema get as that is very big)..

small quick wins

---

app/config/config.yml
app/config/config_test.yml
composer.json
composer.lock
src/Graviton/CoreBundle/Tests/Controller/TranslatableArrayControllerTest.php
src/Graviton/CoreBundle/Tests/Controller/TranslatableRequiredTest.php
src/Graviton/ExceptionBundle/Listener/ValidationExceptionListener.php
src/Graviton/ExceptionBundle/Resources/config/services.xml
src/Graviton/SchemaBundle/Constraint/ConstraintUtils.php
src/Graviton/SchemaBundle/Constraint/IncrementalDateFieldConstraint.php

`justinrainbow/json-schema` has a new major, this PR bumps it to this new one.
Mostly the same, but the `Factory` has gone and some things changed with the `RefResolver` (which also doesn't exist anymore)..
I want this because the silly validation message `String value found, but a null is required` is now correct to the user by mentioning both types ;-)

update json schema dep to new major..

---

src/Graviton/SchemaBundle/Constraint/RecordOriginConstraint.php
src/Graviton/SchemaBundle/Tests/Controller/RecordOriginConstraintTest.php

* adding message about forbidden fields

EVO-6707 adding message about forbidden fields

---

app/AppKernel.php
app/config/config.yml
app/config/config_dev.yml
composer.json
composer.lock

graviton does not have any assets. This bundle is a remanence from symfony/standard-edition.

Remove all traces of assetic-bundle I found

---

composer.json
composer.lock

Update to current PHPUnit version

---

src/Graviton/MigrationBundle/Command/MongodbMigrateCommand.php

the important part is this:
```php
$migrateInput->setInteractive($input->isInteractive());
```
thus, migrations for again for a non-interactive input..
also, if the migration itself has exit code `!=0`, we continue but collect the error information to show it at the end.
note that if exceptions happen, the migration process still makes a full stop.

make migrations run non-interactively

---

src/Graviton/GeneratorBundle/Resources/skeleton/document/DocumentBase.php.twig
src/Graviton/SchemaBundle/Document/Schema.php

We do have a correct Validation in place.
Add fast return for null property due to magic getter in i18listener

Remove unneeded Exception in generated Document

---

src/Graviton/RabbitMqBundle/DependencyInjection/Compiler/DocumentEventMapCompilerPass.php
src/Graviton/RabbitMqBundle/Tests/DependencyInjection/Compiler/DocumentEventMapCompilerPassTest.php

Patch request was not emitting update event.

AMQP Add missing event Patch as Update event

---

src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php

fix error case in generator hash detection where a definition was removed. we need to alter the bundlebundle accordingly

update bundlebundle correctly on definition removal

---

src/Graviton/MigrationBundle/Command/MongodbMigrateCommand.php

scan command should **not** be dependant of `getcwd()`!.. this changes that ;-)

change where/how we search for migrations.yml files..

---

src/Graviton/I18nBundle/Listener/I18nSerializationListener.php

The visitor can only accept 1 add element in used version of JMS serialiser.
Newer version have setData, hasData check and the older used version only add.
To solve the issue a try catch wrapping the "add" is needed.

EVO-8921 Error on serialise big elements with same reference naming

---

src/Graviton/RestBundle/Controller/RestController.php

We do still have some issues on PUT requests, so I have added a lock before even the check request.

EVO-8323 Adding a bit faster lock on put request

---

src/Graviton/FileBundle/Manager/RequestManager.php

application/json uploads should be parsed, not all content data

Allow upload off json files

---

src/Graviton/RabbitMqBundle/Tests/Controller/EventStatusControllerTest.php
src/Graviton/RestBundle/Controller/RestController.php
src/Graviton/SchemaBundle/Tests/Controller/IncrementalDateFieldConstraintTest.php

, if object is not modified we should get response Not Modified

EVO-9552 Patch request

---

composer.json
composer.lock

the repo in composer.json is not used anymore; let's remove it as it will vanish soon..

remove unused repo; rewrite lock with new composer version

---

composer.lock
src/Graviton/SchemaBundle/Constraint/RecordOriginConstraint.php
src/Graviton/SchemaBundle/Tests/Controller/RecordOriginConstraintTest.php

When updating a record and posting none UTC date time we where comparing with UTC.
Converting here to UTC. Test added for recursive testing.

EVO-9833 Constrain date time validation.

---

app/config/config.yml
app/config/config_test.yml
src/Graviton/DocumentBundle/Resources/config/services.xml
src/Graviton/SchemaBundle/Tests/Controller/IncrementalDateFieldConstraintTest.php
src/Graviton/SchemaBundle/Tests/Controller/RecordOriginConstraintTest.php

* change the collection cache adapter for test environment
* fix namespace in 2 tests and add timezone aware test for incrementaldate

change cache collection adapter for tests

---

app/config/config.yml
app/config/config_test.yml
app/config/parameters.yml.dist
composer.json
composer.lock
src/Graviton/CoreBundle/Resources/config/services.xml
src/Graviton/DocumentBundle/Resources/config/services.xml
src/Graviton/I18nBundle/Resources/config/services.xml
src/Graviton/ProxyBundle/Resources/config/services.xml
src/Graviton/SchemaBundle/Resources/config/services.xml

support more flexible caching options and support redis, also via params

add cache flexibilization and redis support

---

src/Graviton/RestBundle/Controller/RestController.php

This solves the long tests and patches being locked until cache lock expire.

Patch request locked for to long.

---

README.md

URL change for the new location of Docs and api info

Docs have been moved to new location.

---

src/Graviton/GeneratorBundle/Command/GenerateBuildIndexesCommand.php
src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig

indexes underscore field db name not allowed.

For never version of MongoDB 

---

src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
src/Graviton/I18nBundle/Listener/AcceptLanguageRequestListener.php
src/Graviton/I18nBundle/Tests/Controller/LanguageControllerTest.php

(cherry picked from commit 83e195b)

fix so we always assume 'en' to be present in acceptable languages

---

web/app.php

as requested by findings from @clementedalmagro

don't trust forwarded header

---

src/Graviton/AnalyticsBundle/Controller/DefaultController.php
src/Graviton/AnalyticsBundle/Listener/HomepageRenderListener.php
src/Graviton/AnalyticsBundle/Resources/config/routing.yml
src/Graviton/AnalyticsBundle/Resources/config/services.yml
src/Graviton/AnalyticsBundle/Tests/Controller/DefaultControllerTest.php
src/Graviton/CoreBundle/Controller/MainController.php
src/Graviton/CoreBundle/Event/HomepageRenderEvent.php
src/Graviton/RestBundle/Service/RestUtils.php

(see title)
also, add response for OPTIONS request

re-instate and adapt the listener so analytics stuff will show on homepage

---

.travis.yml
app/AppCache.php
app/config/config.yml
composer.json
composer.lock

new dep bumps

---

phpunit.xml.dist
src/Graviton/AnalyticsBundle/Manager/AnalyticsManager.php
src/Graviton/AnalyticsBundle/Model/AnalyticModel.php
src/Graviton/AnalyticsBundle/Resources/config/services.yml
src/Graviton/AnalyticsBundle/Tests/Model/AnalyticModelTest.php

Added additional test cover.
Added optional Pipeline array configuration for aggregations.

Added optional Pipeline or Aggregation query.

---

.travis.yml
composer.json
composer.lock
src/Graviton/CoreBundle/Listener/JsonExceptionListener.php
src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php

Added integer and float support for Search RQL
Added minor update for travis
Added better db reference error on missing mongo DBREF server error 500.

php rql parser v2.3.1 integers

---

src/Graviton/I18nBundle/Listener/I18nSerializationListener.php

Small "add" to avoid a exception try catch

Remove deprecated warning from serialiser

---

src/Graviton/CoreBundle/Tests/Controller/VersioningDocumentsTest.php
src/Graviton/SchemaBundle/Constraint/ConstraintUtils.php
src/Graviton/SchemaBundle/Constraint/VersionServiceConstraint.php

shall replace #598 as it introduces less changes and keeps the concerns seperated

versioning handling on patch

---

src/Graviton/ProxyBundle/Controller/ProxyController.php

we maybe have something strange there.. better change that..

only set port if we have something that makes sense..

---

src/Graviton/SecurityBundle/Authentication/Strategies/MultiStrategy.php
src/Graviton/SecurityBundle/Resources/config/services.yml

Missing Strategy in Multi. Needed for other auth method

EVO-11759 : Authentication Multi need all strategies.

---

app/config/config.yml
app/config/parameters.yml.dist
composer.json
composer.lock
src/Graviton/FileBundle/Manager/FileManager.php
src/Graviton/FileBundle/Resources/config/services.yml

For deployment scenarios and mostly for minio.io compat..

Bring configurable S3 support back for /file - defaults are all still the same

---

src/Graviton/CoreBundle/Tests/Controller/PrimitiveArrayControllerTest.php
src/Graviton/DocumentBundle/Entity/Hash.php
src/Graviton/DocumentBundle/Resources/config/services.yml
src/Graviton/DocumentBundle/Serializer/Handler/HashHandler.php
src/Graviton/DocumentBundle/Tests/Serializer/Handler/HashHandlerTest.php
src/Graviton/DocumentBundle/Types/HashType.php
src/Graviton/RestBundle/Controller/RestController.php

finally solve the problem we were facing quite long: successfully render empty objects and arrays.

EVO-11896 - empty object rendering

---

.travis.yml
app/console
composer.json
composer.lock
src/Graviton/AnalyticsBundle/Resources/config/services.yml
src/Graviton/DocumentBundle/Resources/config/services.yml
src/Graviton/ExceptionBundle/Resources/config/services.yml
src/Graviton/FileBundle/Resources/config/services.yml
src/Graviton/GeneratorBundle/Resources/config/config.yml
src/Graviton/GeneratorBundle/Resources/config/services.yml
src/Graviton/GeneratorBundle/Resources/skeleton/bundle/config.xml.twig
src/Graviton/I18nBundle/Resources/config/services.yml
src/Graviton/PersonBundle/Resources/config/config.yml
src/Graviton/RestBundle/Resources/config/services.yml
src/Graviton/SchemaBundle/Resources/config/services.yml
src/Graviton/SecurityBundle/Resources/config/services.yml
src/Graviton/TestBundle/Test/GravitonTestCase.php
web/app.php
web/config.php

update all deps except symfony.. we will skip 3.3 and go directly to 3.4 when ready..

update all *but* symfony

---

.travis.yml
composer.json
composer.lock
src/Graviton/ProxyBundle/Adapter/Guzzle/GuzzleAdapter.php
src/Graviton/ProxyBundle/Controller/ProxyController.php
src/Graviton/ProxyBundle/Definition/Loader/HttpLoader.php
src/Graviton/ProxyBundle/Resources/config/parameters.yml
src/Graviton/ProxyBundle/Resources/config/services.yml
src/Graviton/ProxyBundle/Tests/Definition/Loader/HttpLoaderTest.php

fix problem with updates in psr/guzzle - replace jenssegers lib with our own small one..

EVO-12166 - fix querystring in proxy

---

app/config/config_dev.yml
app/config/config_prod.yml
app/config/config_test.yml
app/config/parameters.yml.dist
composer.json
composer.lock
src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php
src/Graviton/RabbitMqBundle/Resources/config/services.yml
src/Graviton/RabbitMqBundle/Tests/Controller/EventStatusControllerTest.php
src/Graviton/RabbitMqBundle/Tests/Listener/EventStatusLinkResponseListenerTest.php

Expose more parameters so we change how the URLs are sent via RabbitMQ.. gives more flexibility on certain deployment scenarios
Also update deps and simplify logging in prod env

queue urls, logging, deps

---

composer.json
composer.lock
src/Graviton/DocumentBundle/Resources/config/services.yml
src/Graviton/DocumentBundle/Service/CollectionCache.php
src/Graviton/RestBundle/Controller/RestController.php
src/Graviton/RestBundle/Model/DocumentModel.php
src/Graviton/RestBundle/Tests/Controller/AsyncLockingTest.php

try to handle locking things a bit different in the hopes it will hope for the seen issue..
add a test for async access to /event/status

EVO-12345 - async test

---

app/config/parameters.yml.dist
src/Graviton/AnalyticsBundle/Exception/AnalyticUsageException.php
src/Graviton/AnalyticsBundle/Manager/ServiceManager.php
src/Graviton/CoreBundle/Listener/JsonExceptionListener.php

* correct cache key based on request param in analytic
* change exception in usage and ignore for sentry

cache fixing exception cleaning

---

app/config/config.yml
app/config/parameters.yml.dist
composer.json
composer.lock
src/Graviton/AnalyticsBundle/Manager/AnalyticsManager.php
src/Graviton/AnalyticsBundle/Manager/ServiceManager.php
src/Graviton/AnalyticsBundle/Model/AnalyticModel.php
src/Graviton/AnalyticsBundle/Resources/config/services.yml
src/Graviton/AnalyticsBundle/Tests/Controller/DefaultControllerTest.php
src/Graviton/DocumentBundle/Resources/config/parameters.yml
src/Graviton/DocumentBundle/Resources/config/services.yml
src/Graviton/DocumentBundle/Serializer/Handler/DateHandler.php
src/Graviton/DocumentBundle/Service/DateConverter.php

* default values
* date parsing on input and output
* pipeline definition in a separate file

More aggregation features

---

composer.json
composer.lock
src/Graviton/AnalyticsBundle/Controller/DefaultController.php
src/Graviton/AnalyticsBundle/Manager/AnalyticsManager.php
src/Graviton/AnalyticsBundle/Manager/ServiceManager.php
src/Graviton/AnalyticsBundle/Model/AnalyticModel.php
src/Graviton/AnalyticsBundle/ProcessorInterface.php
src/Graviton/AnalyticsBundle/Resources/config/services.yml
src/Graviton/AnalyticsBundle/Tests/AnalyticsTestProcessor.php
src/Graviton/AnalyticsBundle/Tests/Controller/DefaultControllerTest.php
src/Graviton/CoreBundle/Resources/config/parameters.yml
src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.yml.twig
src/Graviton/I18nBundle/Resources/config/parameters.yml

Added to aggregation
* "multi pipelines" (multiple pipelines in one service)
* optional php processors to process those results
* optional params, possible to remove parts of the pipeline if param is not set by user
* date comparisons and handling

Aggregation processing

---

src/Graviton/CoreBundle/Listener/JsonExceptionListener.php
src/Graviton/CoreBundle/Tests/Controller/DatetimeDeserializationControllerTest.php
src/Graviton/DocumentBundle/Resources/config/services.yml
src/Graviton/DocumentBundle/Serializer/Handler/DateHandler.php

more verbosity, accept weaker datetime format again

---

app/config/parameters.yml.dist
composer.json
composer.lock
src/Graviton/DocumentBundle/Resources/config/services.yml
src/Graviton/DocumentBundle/Service/SolrQuery.php
src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php

* don't quote search query
* catch formatted numbers (try to)
* make fuzzy bridge configurable

minor fixes to solr queries

---

composer.json
composer.lock
src/Graviton/DocumentBundle/Listener/RqlSearchNodeListener.php
src/Graviton/DocumentBundle/Resources/config/services.yml
src/Graviton/DocumentBundle/Tests/Listener/RqlSearchNodeListenerTest.php
src/Graviton/RestBundle/Service/QueryService.php

upon solr search, create aggregation pipeline using builder to correctly sort the results

solr aggregation sort fix

---

src/Graviton/DocumentBundle/Service/SolrQuery.php
src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php
src/Graviton/RestBundle/Service/QueryService.php

* fix Link headers with all search modes
* fix x-record-count/x-total-count headers

correct headers for total counts

---

app/config/parameters.yml.dist
composer.json
composer.lock
src/Graviton/DocumentBundle/Resources/config/services.yml
src/Graviton/DocumentBundle/Service/SolrQuery.php
src/Graviton/DocumentBundle/Tests/Service/SolrQueryTest.php

some behavior changes for solr query handling - and added a test

solr changes

---

app/config/config_test.yml
app/config/parameters.yml.dist
composer.json
composer.lock
src/Graviton/CoreBundle/Resources/config/services.yml
src/Graviton/GeneratorBundle/Definition/JsonDefinition.php
src/Graviton/GeneratorBundle/Definition/JsonDefinitionField.php
src/Graviton/GeneratorBundle/Definition/Schema/Field.php
src/Graviton/GeneratorBundle/Definition/Schema/Service.php
src/Graviton/GeneratorBundle/Resources/config/serializer/Definition.Schema.Field.xml
src/Graviton/GeneratorBundle/Resources/config/serializer/Definition.Schema.Service.xml
src/Graviton/GeneratorBundle/Resources/skeleton/model/schema.json.twig
src/Graviton/GeneratorBundle/Tests/Definition/DefinitionElementTest.php
src/Graviton/GeneratorBundle/Tests/Definition/JsonDefinitionFieldTest.php
src/Graviton/GeneratorBundle/Tests/Definition/JsonDefinitionRelTest.php
src/Graviton/RestBundle/Service/RestUtils.php
src/Graviton/SchemaBundle/Document/Schema.php
src/Graviton/SchemaBundle/Model/SchemaModel.php
src/Graviton/SchemaBundle/Resources/config/serializer/Document.Schema.xml
src/Graviton/SchemaBundle/Resources/config/services.yml
src/Graviton/SchemaBundle/SchemaUtils.php

allows to override the `required` status of fields depending on user input data. that is done via the concept of 'schema variations'.
a service definition using this can be seen here 
https://github.com/libgraviton/GravitonTestServicesBundle/blob/v2.1.0/Resources/definition/TestCaseSchemaVariation.json

flexible schema variations

---

src/Graviton/SchemaBundle/Tests/Controller/SchemaVariationsTest.php

add missing test for schema variation

---

composer.json
composer.lock
src/Graviton/DocumentBundle/Service/SolrQuery.php
src/Graviton/DocumentBundle/Tests/Service/SolrQueryTest.php

allow own operators (NOT/OR and so on) as well as gt/lt and field queries

extended solr syntaxes

---

php.ini
src/Graviton/GeneratorBundle/Twig/GeneratorExtension.php

make sure we don't cascade deletes..

---

app/config/parameters.yml.dist
composer.json
composer.lock
src/Graviton/RestBundle/Listener/RestrictionListener.php
src/Graviton/RestBundle/Resources/config/services.yml
src/Graviton/RestBundle/Tests/Controller/RestrictionListenerUnitTest.php
src/Graviton/TestBundle/Test/GravitonTestCase.php

Introduce new LTE (less then equal) restriction mode (in addition to the EQ mode); add more flags to customize restriction behavior

restriction tests and new features

---

src/Graviton/CoreBundle/Resources/definition/ExternalLinks.json

added permission field
