- src/Graviton/CoreBundle/Controller/MainController.php
- src/Graviton/CoreBundle/Resources/config/services.xml
- src/Graviton/CoreBundle/Service/CoreUtils.php
We had a version determination in the MainController. this is clearly the wrong place..
So this contains
* A new CoreUtils service containing a getVersion() method - yes, using the same code as before
* Let MainController use that service
This is preparation so swagger and others can display the same version to the user..
> externalize getVersion()

- composer.json
- composer.lock
Clean some legacy things:
* fix ``license`` field
* remove ``doctrine/doctrine-bundle`` (only needed for orm)
* fix ``jms/serializer-bundle`` version to ">=0.13 <2"
* remove ``symfony/icu`` (obsolete since at symfony 3.5)
* remove ``nulpunkt/monolog-elasticsearch-logstashformat`` (not currently used, we can always re-add)
* fix all things in ``require-dev`` to versions and remove ``phpmd/phpmd``
* add git-flow style ``non-feature-branches`` config
I was hoping to get better performance from composer but that didn't work out. This has some worthwhile changes anywho.
> update composer deps

- src/Graviton/I18nBundle/Tests/Controller/TranslatableControllerTest.php
- src/Graviton/RestBundle/Routing/Loader/ActionUtils.php
- src/Graviton/RestBundle/Routing/Loader/BasicLoader.php
This is based on a case found by the frontend team. For some reasons GravitonRestBundle was not generating rules for OPTIONS requests with id. This lead to them not getting proper CORS headers in the responses.
I'm testing with a small test that is based on getting OPTIONS from ``/i18n/translatable/i18n-de-German`` since this is the module where the problems where first identified.
> fix CORS headers on OPTIONS request with id

- composer.json
- composer.lock
composer should actually support both versions (ie ">=0.13 <2" and ">=0.13,<2", but the version without a comma is broken in composer-1.0.0-alpha9. For us the easiest fix is to just not use the non working syntax
and use a form that works in the composer version that the build pack installs.
> fix multi version constraint in composer.json

- src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php
hopefully last thing needed there.. currently, a warning output is produced because the param is not really existing.. this should fix that, shouldn't have removed that in the first place..
> we still need to check for param existence to not trigger a warning output..

- src/Graviton/RestBundle/DependencyInjection/Compiler/RestServicesCompilerPass.php
- src/Graviton/RestBundle/GravitonRestBundle.php
- src/Graviton/RestBundle/Resources/config/services.xml
- src/Graviton/RestBundle/Routing/Loader/BasicLoader.php
- src/Graviton/RestBundle/Tests/DependencyInjection/Compiler/RestServicesCompilerPassTest.php
- src/Graviton/RestBundle/Tests/DependencyInjection/Compiler/WebServicesCompilerPassTest.php
Load routes tagged as ``graviton.rest`` during container compilation phase by using a compiler pass.
We'll still need to identify all the places where we need to clear the cache after this change. One area is certainly after generating bundles. I'm working on adding that to ``graviton:generate:`` on a branch as well.
For the time being we'll have to run ``app/console cache:clear`` after running the generators.
With this SYMFONY_ENVs aren't broken anymore. I was able to run graviton under the prod env.
> CompilerPass to find services needed for generating routes

- src/Graviton/GeneratorBundle/Definition/JsonDefinition.php
These don't change the fact that we need to implement some kind of validation
and logging in these areas of our code.
If one happens to have a small error in a definition it should not take that much
debugging to figure it out :)
I think we already have a GRV on this, for now this is what happend due to a typo
of mine that i realized to late.
> throw at least some errors in graviton:generate:dynamicbundles

- composer.json
- composer.lock
I received the following error after `composer install` and loading the fixtures afterwards:
```
[JMS\Serializer\Exception\RuntimeException]                                 
You must define a type for GravitonDyn\ModuleBundle\Document\Module::$key.
```
Changing the order of install commands as in this PR fixes this. I'm not sure why, but it does it ;-)
The error currently prevents the fixtures from getting loaded, so we need this fix asap..
> fix install flow

- src/Graviton/SwaggerBundle/Command/SwaggerCopyCommand.php
The path to the `vendor` dir differs in wrapper context, this fixes that..
AFAIK there is no programmatic way to know if we're the main package or a dependency, so this is a no-fuss way..
> swagger dist path

- .bp-config/nginx/server-locations.conf
Now that we host it for itself we need to make it reachable from https://swagger.nova.scapp.io/.
This fixes that for cf and will need adding to all wrappers that target cf. We still need to solve it for wrappers that push elsewhere (ie. docker et al).
> return cors header for swagger.json

- src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php
- src/Graviton/RestBundle/Listener/SelfLinkResponseListener.php
- src/Graviton/RestBundle/Resources/config/services.xml
- src/Graviton/SchemaBundle/Listener/CanonicalSchemaLinkResponseListener.php
- src/Graviton/SchemaBundle/Listener/SchemaContentTypeResponseListener.php
- src/Graviton/SchemaBundle/Resources/config/services.xml
This should help a bit with our phpunit performance issues. Some of them seem to stem from the
fact the container builder does multiple passes on ContainerAware things. This gets rid of a small
part of them. It won't make phpunit fast, but it is a step in the right direction.
File this under cleaning up legacy code from the olden days when injecting the container was still
the rage.
> remove container dependency from listeners

- .travis.yml
- app/Resources/doc/DEVELOPMENT.md
- composer.json
- composer.lock
- dev-check.sh
Also fixes wrapper cases that don't themselves have phpcs installed.
I'm doing it like so since that was recommended on the composer issue
that talked about adding a "scripts-dev" node to composer.json. I can't
seem to find that again though.
This also fixes cloud pushes directly from the graviton repo and I use
those lots for dev.
> fix --no-dev composer install cases

- src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php
Now, please consider my thoughts when looking into this.. it's a no-brainer actually ;-)
**What we need**
In specific Graviton wrappers we need to be able to exclude certain services from generating a controller.  In ml3k context, we do this by overriding the JSON file (inheritance there) and setting the `service.routerBase` to `null`. This here adds the same ability to Graviton, but obviously in a different fashion as we don't have JSON file inheritance here.
It's crucial we generate all `Documents` from *all* available JSON files - but *don't* generate a `Controller` to it as those `Document` classes are needed in logic controllers to do their work. See elaboration below.
**What solutions I considered**
Now, why is this an environmental setting influencing the Generator? I considered …
> added ability to provide a wrapper specific service whitelist

- app/config/config.yml
- app/config/parameters.yml.dist
This removes the naming strategy param from dist. I'm doing this since the user won't need to be able to configure this anyhow.
> Remove serializer naming strategy from parameters.yml.dist

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/ExceptionBundle/Exception/MalformedInputException.php
- src/Graviton/RestBundle/Listener/ValidationRequestListener.php
- src/Graviton/TestBundle/Client.php
Currently, if a client posts malformed json to a service, he gets (sadly as HTML currently) the following:
```
Argument 1 passed to Graviton\RestBundle\Validator\JsonInput::checkDocument() must be of the type array, null given, called in /home/dn/git/graviton2/src/Graviton/RestBundle/Validator/JsonInput.php on line 79 and defined (500 Internal Server Error)
```
this is unspecific and doesn't help the consumer.. this PR addresses this and throws an explicit Exception containing the json decode error..
> report malformed json

- src/Graviton/I18nBundle/Listener/PostPersistTranslatableListener.php
I had the [InvalidArgumentException thrown by Symfony finder](http://api.symfony.com/2.6/Symfony/Component/Finder/Finder.html#method_in) if the directory it must search for files doesn't exist.. As this is thrown in app/console context, the Exception is unhandled and it leads to the stop of the fixture loading process. 
We can safely catch that exception and continue normal operation there..
> fix translation load exception

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/RestBundle/Controller/RestController.php
This bug was encountered during a issue testing from Kyrill..
For some reason, he made a PUT request with a payload without an "id" field (as said, in the payload) - but obviously specifying one in the URI he requested. 
Graviton in this case inserted a new record and returned this one (because of the way we insert it in `DocumentModel`).  It's wrong to insert a record on PUT.
This fixes that, ensuring that we take the ID from the URI request if it's not on the payload already. I also added tests that ensure that behavior. If the entity on question doesn't have a `setId()` function and there is no ID in the payload, we quit and tell the user.
Normally, a read/write entity would always have a `setId()` function, I just want to make it more reliable there as this is not *always* the case..
> ensure we don't create a new record when there is no ID on PUT request..

- composer.json
- composer.lock
There was in fact a bug in the last ``composer update`` we merged.
This PR skips symfony/symfony v2.5.6 and thus fixes pushing to the cloud.
I still need to sift through https://github.com/symfony/symfony/compare/v2.6.5...v2.6.6 and figure out what where this issue is coming from (or just create an issue upstream if I can't). It could be https://github.com/symfony/symfony/commit/ce2764d416c7287d2126e3d1fb9338f329c1d80f but I need to check...
> Fix cf deploy once again

- src/Graviton/I18nBundle/Resources/config/schema/Translatable.json
- src/Graviton/I18nBundle/Tests/Controller/TranslatableControllerTest.php
This one was simply too small to not just do.
> Require ID in /i18n/translatable schema

- .gitignore
Just configure a global file and add something:
```
git config --global --add core.excludesfile ~/.gitignore_global
echo '.*.sw?' >> ~/.gitignore_global
```
> Remove developer-local ignores after documenting ~/.gitignore_global

- dev-cleanstart.sh
I just stared at a ``Composer\DependencyResolver\SolverProblemsException`` due to an issue that was long gone. Seriously, I'm adding that you should install composer globally to our guidelines ASAP.
> Use global composer install

- app/config/parameters.yml.dist
- composer.json
- composer.lock
- src/Graviton/DocumentBundle/DependencyInjection/GravitonDocumentExtension.php
I had to disable the update to symfony-2.6.6 in 616a5d50fd766987dec837cdb7895a05044632c0 due to our way of overriding params from the env being broken due to upstream changes.
Here I'm doing a small change that adds another level of indirection to how we load vars from VCAP_SERVICES. This enables us to keep the mongodb config overridable and still specify an overridden config through env.
We might be using similar patterns in docker images at a later point as well.
> symfony 2.6.6 fix

- src/Graviton/GeneratorBundle/Definition/JsonDefinition.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
Use it like this.
```js
{
"id": "Foo",
"description": "Foo service",
"service": {
"readOnly": false,
"routerBase": "/acme/foo/",
"parent": "graviton.acme.controller.foo",
]
}
}
```
Wield it wisely and remember that we still need to put work into RestController to make this more sane.
> Allow explicit parent service in services from jsondef

- composer.json
- composer.lock
- phpunit.xml.dist
Our suite is slow already. This displays the worst offenders and at least makes them visible. We still need real fixes here and also things like test parallelization but those will be left for other PRs.
> Use phpunit-speedtrap to display slow tests

- app/AppKernel.php
- app/config/config.yml
- app/config/parameters.yml.dist
- composer.json
- composer.lock
To enable errbit logging you need to set ``ERRBIT_API_KEY`` and ``ERRBIT_HOST``.
I already have errbit deployed to the cloud thru jenkins using a blue/green deploy and graviton-develop should also be setup properly for this to work on the next deploy. The code I used to deploy errbit is in a fork [over here](https://github.com/gravity-platform/errbit) and in jenkins' config.
We need to test that everything is running stable-ish before this makes sense but my first tests look very promising.
Contact me for access so you can review this using my cf instance of errbit. At the moment I have a prod and an unstable version available, I'll add develop if we need it (ie. on the next large upstream merge of errbit).
> Add and configure eo/airbreak-bundle

- src/Graviton/PersonBundle/Controller/AbstractCustomerController.php
- src/Graviton/PersonBundle/Resources/config/services.xml
- src/Graviton/PersonBundle/Tests/Controller/AbstractCustomerControllerTest.php
This is complete with docs and and an absolutely rudimentary testcase for the new ``Graviton\PersonBundle\Controller\AbstractCustomerController``.
It can be used in a JsonDefinition as follows.
```js
{
// ...
"service": {
// ...
"baseController": "\\Graviton\\PersonBundle\\Controller\\AbstractCustomerController",
"parent": "graviton.person.controller.abstractcustomer",
// ...
},
// ...
}
```
The corresponding internal pull request is incoming soon as well.
Both of them will enable me to put [GRV-1764](https://issue.swisscom.ch/browse/GRV-1764) into review.
I'm going to assigning this to @samsamann when the builds are through since he should be in the loop on this.
> Implement AbstractCustomerController in PersonBundle

- src/Graviton/GeneratorBundle/Command/GenerateResourceCommand.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator/FieldJsonMapper.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator/FieldMapper.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator/FieldMapperInterface.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator/FieldNameMapper.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator/FieldTypeMapper.php
- src/Graviton/GeneratorBundle/Resources/config/services.xml
- src/Graviton/GeneratorBundle/Tests/Generator/ResourceGenerator/FieldJsonMapperTest.php
- src/Graviton/GeneratorBundle/Tests/Generator/ResourceGenerator/FieldMapperTest.php
- src/Graviton/GeneratorBundle/Tests/Generator/ResourceGenerator/FieldNameMapperTest.php
- src/Graviton/GeneratorBundle/Tests/Generator/ResourceGenerator/FieldTypeMapperTest.php
This replaced my much older PR #34 and finally refactors a rather complex lambda function in ``Graviton\GeneratorBundle\Generator\ResourceGenerator``.
I should probably avoid using such lambda function since it never takes long until someone else comes along and adds much more complexity to a short function without doing the refactor that would be needed in that moment.
This cleans up one such occurrence and replaces it with heaps of tested code.
This is still not perfect (ie. it still uses ``array_map`` and the command is still not configured through the di) so it's not as complete as #34 was. Nevertheless I feel like this already is worthy to merge since it makes the reason I started #34 sane again (aka field-mapping is now tested and thus documented).
> refactor resource generator field mapper

- src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator/ParameterBuilder.php
- src/Graviton/GeneratorBundle/Resources/config/services.xml
- src/Graviton/GeneratorBundle/Tests/Generator/ResourceGenerator/ParameterBuilderTest.php
Splits out the ``$parameters`` building part of ``ResourceGenerator::generate()`` into its own class.
While the new ``ParameterBuilder`` class could be cleaner and more decoupled, this is nevertheless better than what we had before.
I'm not going any further on this due to the fact that ~~``ResourceGenerator``~~``ResourceGenerator::generate()`` isn't our worst smell anymore and also because the remaining refactor is rather small and straightforward.
If anyone wants to pick up the torch and carry on from here, you're welcome to refactor ``ParameterBuilder::setParameter()`` into something less complex.
> parameter builder for resource generator

- src/Graviton/RestBundle/Resources/config/services.xml
- src/Graviton/RestBundle/Service/RestUtils.php
We still need to get rid of container use in ``getControllerFromRoute``. I might do a factory on that but have not really decided how to proceed yet.
I'm pretty sure this is also done in a similar fashion elsewhere so that adding such a factory will probably have other implications elsewhere as well.
At this stage the most valuable part of this PR is probably adding the ``final`` keyword. While the rest doesn't fully achieve the target of getting rid of the container-dep it still seems worthy.
> Switch to constructor injection, add final keyword and don't use container in most cases

- src/Graviton/CoreBundle/Controller/MainController.php
- src/Graviton/CoreBundle/Resources/config/services.xml
- src/Graviton/CoreBundle/Tests/Controller/MainControllerTest.php
I would have also marked the Controller as final if it the final keyword hadn't been broken by proxy-object based testing (which I believe to be silly in itself, IMHO things should either be public and directly tested or in the need of refactoring as they are not properly exposed, but that discussion is for another time).
Also, if you're interested, this is the ``.git/hooks/pre-commit`` I wrote after 4ae30f9 failed on travis:
```bash
exec /usr/local/bin/composer check
```
> Remove container dependency in MainController

- composer.json
- composer.lock
- src/Graviton/DocumentBundle/Tests/Types/ExtReferenceTest.php
- src/Graviton/DocumentBundle/Types/ExtReference.php
With these changes using $ref references that point to a service that has a camel-cased collection name in MongoDB should work.
> Fix camel case services in extref

- composer.lock
Makes [GRV-1786](https://issue.swisscom.ch/browse/GRV-1786) ready for review. I'll still have to deploy it though.
> Add colon (:) support in rql strings

- src/Graviton/DocumentBundle/DependencyInjection/Compiler/ExtRefFieldsCompilerPass.php
This fixes the compiler pass so it also works for generated bundles that have mixed-case document names.
This is not a perfect solution to the problem, I'll have to refactor this when I finish adding forms support since I need it there anyway...
> use symfony/finder in ExtRefFieldsCompilerPass

- src/Graviton/ExceptionBundle/Exception/DeserializationException.php
- src/Graviton/ExceptionBundle/Exception/MalformedInputException.php
- src/Graviton/ExceptionBundle/Exception/NoInputException.php
- src/Graviton/ExceptionBundle/Exception/NotFoundException.php
- src/Graviton/ExceptionBundle/Exception/RestException.php
- src/Graviton/ExceptionBundle/Exception/RestExceptionInterface.php
- src/Graviton/ExceptionBundle/Exception/RestExceptionTrait.php
- src/Graviton/ExceptionBundle/Exception/SerializationException.php
- src/Graviton/ExceptionBundle/Exception/ValidationException.php
This makes our home-baked exceptions use symfonys HttpException as base.
In itself this does not change much, it's part of the larger picture of us refactoring parts to use more framework and less home-made stuff.
> Use proper HttpException as base

- src/Graviton/RestBundle/Listener/CorsResponseListener.php
This should fix ETag/If-None-Match based caching in cross-origin requests.
> Allow If-None-Match in CORS headers

- app/AppKernel.php
graviton should honor the `date.timezone` php setting and not fix itself to UTC just like that. we still fix to UTC if there's no timezone set.
I didn't use `date_default_timezone_get()` as it takes into account too much, like the `TZ` env variable of the webserver user and so on - we just want to honour `date.timezone` IMHO..
> honor date.timezone setting if it's around

- app/config/config.yml
This helps us fail over in cases like replica set fail overs.
See http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html#retrying-connections-and-queries for more info.
Should allow us to resolve https://errbit.nova.scapp.io/apps/5559a49731386c002b170000/problems/555dc00731386d002a7d0000.
> Retry MongoDB operations

- .travis.yml
- composer.json
- composer.lock
Both are allowed to fail (and even do so for various reasons) and both get a bit further along than before.
This should help us keep track of when mongodb/doctrine stops blocking both platforms.
> Work on php 7 and hhvm on travis

- src/Graviton/I18nBundle/Listener/AcceptLanguageRequestListener.php
- src/Graviton/I18nBundle/Resources/config/services.xml
This makes using curl make a bit more sense and stops us from returning invalid content.
ie.
```
{ "name": [] }
```
becomes
```
{ "name": { "en": "Name" } }
```
> Return defaultLocale if no locale requested

- src/Graviton/CoreBundle/Document/App.php
- src/Graviton/CoreBundle/Document/Product.php
- src/Graviton/CoreBundle/Resources/config/schema/Product.json
- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
- src/Graviton/FileBundle/Controller/FileController.php
- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.php.twig
- src/Graviton/I18nBundle/Document/Language.php
- src/Graviton/I18nBundle/Document/TranslatableDocumentInterface.php
- src/Graviton/PersonBundle/Controller/AbstractCustomerController.php
- src/Graviton/RestBundle/Controller/RestController.php
- src/Graviton/RestBundle/Resources/config/services.xml
- src/Graviton/SchemaBundle/Document/Schema.php
- src/Graviton/SchemaBundle/Model/SchemaModel.php
- src/Graviton/SchemaBundle/Resources/config/schema/SchemaModel.json
- src/Graviton/SchemaBundle/Resources/config/serializer/Document.Schema.xml
- src/Graviton/SchemaBundle/Resources/config/services.xml
- src/Graviton/SchemaBundle/SchemaUtils.php
- src/Graviton/SwaggerBundle/Command/SwaggerGenerateCommand.php
- src/Graviton/SwaggerBundle/Resources/config/services.xml
- src/Graviton/SwaggerBundle/Service/Swagger.php
This PR aims to make our swagger.json pass as 'valid' from online validation, thus
**See this**
I pushed this branch to the cloud.
Swagger validation result here: http://online.swagger.io/validator/?url=http://graviton-nue-swaggerfix-unstable.nova.scapp.io/swagger.json
If you check http://graviton-nue-swaggerfix-unstable.nova.scapp.io/swagger.json - you'll see that there are the Languages listed inside the 'object' struct of an Translatable (CTRL+F for "translatable")
*Major changes in schema*
* Only output primitive types in the "field" field of the Schema, more specifics are handled in the "format" field.
* Some changes in the Schema schema to conform to spec
* Include Languages in the presentation of the Translatable object (which now has `type: object, format: translatable`)
Todo …
> make swagger json valid & more complete

- src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
- src/Graviton/SchemaBundle/SchemaUtils.php
Changes the schema output so extref fields are prefixed with a ``$`` as they should be...
> dollar in name of extref fields in schema

- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentFormFieldsCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentFormMapCompilerPass.php
- src/Graviton/DocumentBundle/Form/Type/DocumentType.php
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/DocumentFormFieldsCompilerPassTest.php
I still have the issue that the free-form objects are not getting save down to the innermost value... At least with this we throw less errors (it does lose some data though :rage4:)...
I'm opening this PR now since I'm kinda stumped as how to continue. In my opinion we should stop using free-form-services and implement them all.
If anyone has an idea what we can change so it works with deeply nested free-form-fields, I'd be very happy (i tried 'compound' = true to no avail).
> make free-form objects work after introducing forms

- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentFormFieldsCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentFormMapCompilerPass.php
- src/Graviton/DocumentBundle/Form/Type/DocumentType.php
- src/Graviton/DocumentBundle/Form/Type/FreeForm.php
- src/Graviton/DocumentBundle/Resources/config/services.xml
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/DocumentFormFieldsCompilerPassTest.php
@hairmare 
This simple solution seems to work fine to solve the nightmare that began in #167..
Can u pls verify if this works for u too?
Apparently, passing an object structure to a `text` based field imposes no problem at all, passing it through the whole thing ;-)
One could argue why we don't put it in a normal `text` field then, but IMHO it's cleaner to have a dedicated type to "hashes"..
> custom form type for freeform

- src/Graviton/RestBundle/Validator/Constraints/BooleanStrictValidator.php
addViolation is found in ExecutionContextInterface and buildViolation in ConstraintValidator. It's better to code against an interface instead of a concret class.
> coded against interface instead of concret implementation

- src/Graviton/PersonBundle/Resources/config/schema/PersonContact.json
- src/Graviton/PersonBundle/Resources/config/serializer/Document.PersonContact.xml
`PersonContact` seems to be only used in `ShowCase.json` (will update that as soon this one is merged).
To expose `uri` as `$ref` doesn't work anymore since `RestController` doesn't use the serializer anymore.. I don't think it should be `$ref` as this is a "real" link - this one here are (mainly) links but they don't have to be. As it's more a test character, i just render it as `uri` again..
> don't try to rewrite 'uri' to '$ref' in personcontant..

- src/Graviton/CoreBundle/Resources/config/routing.xml
- src/Graviton/CoreBundle/Tests/Controller/MainControllerTest.php
- src/Graviton/RestBundle/Service/RestUtils.php
Makes OPTIONS requests also return CORS-Headers on ``/``. I'm not sure who requested this but had it on a branch and it seems to make sense....
> OPTIONS response for root url

- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentFormFieldsCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentFormMapCompilerPass.php
[see title]
i discovered this one while preparing the ShowCase unit test - apparently, any `reference-one` and `reference-many` in doctrine.xml was not mapped before.. this one fixes that.. ;-)
> make both compiler passes also look at reference-[one|many] xml defs..

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
- src/Graviton/FileBundle/Controller/FileController.php
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig
- src/Graviton/I18nBundle/Tests/Controller/LanguageControllerTest.php
- src/Graviton/RestBundle/Controller/RestController.php
- src/Graviton/RestBundle/Model/DocumentModel.php
as was noted by our customers, PUT now behaves different from POST (returning content instead of Location/Link header)..
This PR tries to make PUT behavior the same as POST. 
This has some urgency, as (in a slightly unrelated matter) some services (as `Consultation`) fail to get there content back on the current PUT implementation is the Serializer struggles to deserialize what comes from Symfony form (ie some dates now seem to be String instead of DateTime)..
@hairmare There seems mystery is happening in `FileControllerTest` ("make array of things writable"). Do you have any insight?  Somehow, when the `links` array is altered and PUT'ted, then GET'ted again, the `links` array has two items - which lead the test to fail.
Obviously, that test needs to pass - but I struggle to understand …
> make PUT to behave like POST

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/RestBundle/Model/DocumentModel.php
currently, the applying of the default value of `perPage` *always* overrides whatever is passed by RQL.. Thus, limiting via RQL is not possible at all currently..
IMHO rql `limit()` should always be the master and should not be overriden by `GET[perPage]`, this PR implements that..
> make sure we don't override rql limit()

- src/Graviton/RestBundle/Service/RestUtils.php
- src/Graviton/SchemaBundle/SchemaUtils.php
This is just a clean cherry pick of #177. And supersedes that as such. It also contains one additional fix in that we could in theory still have embedded docs that require an id.
> Ignore id of embedded documents in schema

- src/Graviton/DocumentBundle/DependencyInjection/Compiler/ExtRefFieldsCompilerPass.php
With this we also support having extref fields in referenced documents and not only in embedded ones.
> Find referenced fields as well as embedded fields in extref mapper

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/GeneratorBundle/Resources/skeleton/validator/validation.xml.twig
- src/Graviton/RestBundle/Controller/RestController.php
- src/Graviton/RestBundle/Validator/Constraints/Id/IdInPost.php
- src/Graviton/RestBundle/Validator/Constraints/Id/IdInPostValidator.php
The problem was that it did an UPDATE request when the user did a POST request with an ID in the payload, what is actually not right. This should solve the problem and returns an error message by validating the request.
> Deny POSTing new documents with id

- src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
- src/Graviton/CoreBundle/Tests/resources/showcase-complete.json
- src/Graviton/CoreBundle/Tests/resources/showcase-incomplete.json
- src/Graviton/CoreBundle/Tests/resources/showcase-minimal.json
- src/Graviton/I18nBundle/Listener/I18nSerializationListener.php
this is a PR that should cover the Generator results by testing our `ShowCase.json` service.
Results found, stuff we need to fix/decide
> ShowCase Unit Test

- src/Graviton/DocumentBundle/DependencyInjection/Compiler/ExtRefFieldsCompilerPass.php
I'm a bit unsure why this is even an issue but am rather too lazy to search for it. I'm pretty sure it has to do with our much more liberal xpath queries regarding the (embed|reference)-{one|many) stuff.
> Make sure we don't have any repeated fields

- src/Graviton/CoreBundle/Resources/definition/Module.json
- src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
- src/Graviton/CoreBundle/Tests/resources/showcase-complete.json
- src/Graviton/CoreBundle/Tests/resources/showcase-incomplete.json
- src/Graviton/CoreBundle/Tests/resources/showcase-minimal.json
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentFormFieldsCompilerPass.php
- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.php.twig
Also fixes some bits and pieces that where in the way of having multiple translatable fields in a single object and some generator stuff.
We'll need to do some serious refactoring on the translatable stuff before it becomes real useable and not as smelly as it is right now, but for the time being this has to make do.
> Make module translatable

- src/Graviton/CoreBundle/Resources/definition/Config.json
- src/Graviton/CoreBundle/Tests/Controller/ConfigControllerTest.php
It was suggested that the encoding of RQL parser specialties (ie the encoding of the dash ["-"] character in an encoded string) is wrongly encoded in the generated Link header.
I added a test to ensure it's correct. As it turns out, the encoding is fine. 
I need to check with the Graviphoton people for an example that gets encoded wrong..
@hairmare You know any wrongly encoded expression?
> ensure RQL encoding is correct in Link header

- composer.json
- composer.lock
- src/Graviton/CoreBundle/Resources/config/services.xml
- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/CoreBundle/Tests/Controller/ConfigControllerTest.php
- src/Graviton/ExceptionBundle/Listener/RqlSyntaxErrorListener.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
- src/Graviton/I18nBundle/Resources/config/services.xml
- src/Graviton/PersonBundle/Resources/config/services.xml
- src/Graviton/RestBundle/Listener/GetRqlUrlTrait.php
- src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php
- src/Graviton/RestBundle/Listener/SelfLinkResponseListener.php
- src/Graviton/RestBundle/Model/DocumentModel.php
- src/Graviton/RestBundle/Resources/config/services.xml
- src/Graviton/RestBundle/Tests/HttpFoundation/LinkHeaderTest.php
The updates to ``graviton/php-rql-parser`` and ``graviton/rql-parser-bundle`` remove quite some cruft and make integrating with the parser much easier.
This PR changes the bare minimum to get everything up and running with the latest parser version. I'm expecting to do some more cleaning over the course of implementing the changes I'm actually after.
Feature wise this does the following things.
It also fixes the issue where ``$`` was already being decoded php all of PHP's magic methods. I originally had that fix in graviton, but It became part of the silly ``$_SERVER`` parsing in [the listener](https://github.com/libgraviton/GravitonRqlParserBundle/blob/develop/src/Listener/RequestListener.php#L60).
> Update parser and parser bundle

- composer.json
- composer.lock
Having this does more harm than good as it stands. It seems that this was copied over from symfony at some stage.
> Fix branch-alias

- composer.json
- composer.lock
- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/CoreBundle/Tests/Controller/ConfigControllerTest.php
- src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
- src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
- src/Graviton/RestBundle/Listener/GetRqlUrlTrait.php
- src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php
- src/Graviton/RestBundle/Listener/SelfLinkResponseListener.php
- src/Graviton/RestBundle/Tests/HttpFoundation/LinkHeaderTest.php
I'm aiming at tagging a new graviton release as soon as this has been merged...
> Remove perPage. page and q param and switch to full query string being rql

- composer.json
- composer.lock
- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/CoreBundle/Tests/Controller/MainControllerTest.php
- src/Graviton/RestBundle/DependencyInjection/Compiler/RqlQueryDecoratorCompilerPass.php
- src/Graviton/RestBundle/DependencyInjection/Compiler/RqlQueryRoutesCompilerPass.php
- src/Graviton/RestBundle/GravitonRestBundle.php
- src/Graviton/RestBundle/Listener/RqlQueryRequestListener.php
- src/Graviton/RestBundle/Resources/config/services.xml
- src/Graviton/RestBundle/Tests/DependencyInjection/Compiler/RqlQueryDecoratorCompilerPassTest.php
- src/Graviton/RestBundle/Tests/DependencyInjection/Compiler/RqlQueryRoutesCompilerPassTest.php
- src/Graviton/RestBundle/Tests/GravitonRestBundleTest.php
- src/Graviton/RestBundle/Tests/Listener/RqlQueryRequestListenerTest.php
`Bad Request` occurs even if I request `/_profiler/f2ef11/search/results?ip=&limit=10`.
This disables RQL parsing for all not "allAction" routes.
I added `RqlQueryRequestListener` that decorates (not overwrites) `Graviton\RqlParserBundle\Listener\RequestListener`.
> 20150812 rql parse route list

- app/config/config.yml
As it turned out, yml config files does support escaping stuff in strings...
With this I can finally mark all the parser errors being reported to errbit as resolved...
> Fix escaping error that made errbit log to much

- src/Graviton/SwaggerBundle/Service/Swagger.php
It looks like swagger has no way to express that a query string should be used as the fully query string.
The proper way would be to document all the possible fields as param using FIQL based syntax. I don't really feel like going down that rabbit hole right now since it would make things rather more complex.
~~For now I'm also preparing a version of swagger-ui that has some code that handles rql params as the special little cookie they are.~~ Turns out that the changes I wanted to implement in swagger-ui where both non-trivial and rather smelly. For now I ended up just removing the param from swagger... This means users will have to test their RQL stuff without swagger-ui.
> Reflect changes in swagger.json

- src/Graviton/GeneratorBundle/Resources/config/serializer/Definition.Schema.Service.xml
- src/Graviton/GeneratorBundle/Resources/config/services.xml
- src/Graviton/GeneratorBundle/Serializer/Handler/ArrayObjectHandler.php
- src/Graviton/GeneratorBundle/Tests/Serializer/Handler/ArrayObjectHandlerTest.php
- src/Graviton/GeneratorBundle/Tests/Serializer/Handler/TestData.php
- src/Graviton/GeneratorBundle/Tests/Serializer/Handler/resources/config/serializer/TestData.xml
This allows to use empty fixtures `{}` (see [File.json](https://github.com/libgraviton/graviton/blob/develop/src/Graviton/FileBundle/Resources/definition/File.json#L9)).
In current implementation, we are losing the type during deserialization and serialization:
```php
// outputs "[[]]"
echo $serializer->serialize(
$serializer->deserialize('[{}]', 'array<array>', 'json'),
'json'
);
````
> 1454 fix empty fixtures

- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig
MongoDB ODM was released [today](https://github.com/doctrine/mongodb-odm/releases).
ID value validation for default strategy (`AUTO`) was changed in:
https://github.com/doctrine/mongodb-odm/commit/3dd6a2f10e14f389d760fb9857d7dbeca9199972
I get the following errors when I try to load fixtures:
```bash
[vagrant@localhost fork]$ composer.phar update
.....
[vagrant@localhost fork]$ app/console doctrine:mongodb:fixtures:load
> purging database
> loading Graviton\I18nBundle\DataFixtures\MongoDB\LoadMultiLanguageData
> loading Graviton\CoreBundle\DataFixtures\MongoDB\LoadProductData
> loading Graviton\I18nBundle\DataFixtures\MongoDB\LoadLanguageData
> loading Graviton\I18nBundle\DataFixtures\MongoDB\LoadTranslatablesApp
> loading Graviton\CoreBundle\DataFixtures\MongoDB\LoadAppData
> loading …
```
> Set default ID strategy to "UUID".

- src/Graviton/CoreBundle/Resources/definition/Module.json
- src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
This way the order of the loaded records is always the same in each run.
This should make travis work as intended again. We noticed this in both #236 and #238...
> Fix module test by using pre-defined identifiers

- src/Graviton/GeneratorBundle/Resources/skeleton/fixtures/LoadFixtures.php.twig
this is a very small PR fixing a minor bug..
if a field is named in a plural way, the current fixture loading process doesn't work as it calls `add{fieldName}()` and `set{fieldName}()`. and those fields get generated in a different name, as the `add*` function is generated in the singularName.
so i made this small change that it only calls the `set*()` function that always has the *correct* name
> fix for loading array fixtures

- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig
we use reltype: 'ref' in most json files.. this quick fixes generates the xml as now expected by doctrine..
> doctrine doesn't honor 'ref-many' anymore, must be 'reference-many'

- src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/ExtRefFieldsCompilerPass.php
- src/Graviton/DocumentBundle/Listener/ExtReferenceSearchListener.php
- src/Graviton/DocumentBundle/Service/ExtReferenceConverterInterface.php
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/ExtRefFieldsCompilerPassTest.php
`ExtReferenceSearchListener` searches for extref in array fields only by first array element (see `ShowcaseControllerTest::testFindByExtref()`) because we generate the following queries:
```json
{
"nestedApps.0.ref.$ref": "App",
"nestedApps.0.ref.$id": "admin"
}
```
I tried to change the query to:
```json
{
"nestedApps.ref.$ref": "App",
"nestedApps.ref.$id": "admin"
}
```
But Doctrine processes such queries so strange:
```php
$repository = $this->container
->get('doctrine_mongodb.odm.default_document_manager')
->getRepository('GravitonDynModuleBundle:Module');
dump(
$repository->createQueryBuilder()
->field('service.gui.ref.$ref')
->equals('A')
->field('service.gui.ref.$id')
->equals('a')
->getQuery()
->getQuery()['query']
);
```
outputs:
```
array:2 [
"service.gui.ref.$ref.$ref" => "A" …
```
> 20150827 fix searching by extref

- src/Graviton/RestBundle/Tests/Validator/ExtReference/ExtReferenceValidatorTest.php
- src/Graviton/RestBundle/Validator/Constraints/ExtReference/ExtReferenceValidator.php
Skipping validation for `null` in `ExtReferenceValidator`.
`null` values should be validated by `NotNullValidator` or `NotBlankValidator`.
> 20150904 ref validation

- composer.lock
- src/Graviton/CoreBundle/Tests/Controller/EmptyObjectControllerTest.php
- src/Graviton/CoreBundle/Tests/Controller/NullExtrefControllerTest.php
- src/Graviton/DocumentBundle/Service/FormDataMapper.php
- src/Graviton/DocumentBundle/Tests/Service/FormDataMapperTest.php
- src/Graviton/GeneratorBundle/Definition/JsonDefinition.php
- src/Graviton/RestBundle/Controller/RestController.php
This fixes array serialization and adds new tests for nulls in `extref`.
@narcoticfresh this pull request depends on https://github.com/libgraviton/GravitonTestServicesBundle/pull/13
> 20150908 empty objects in array

- src/Graviton/FileBundle/Controller/FileController.php
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
Having Location redirect after a PUT request triggered some edge cases in [CORS](http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0).
This makes updating files behave like updating metadata for the sake of replacing documents.
> Fix updating of files through PUT in cors scenarios

- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
- src/Graviton/GeneratorBundle/Resources/skeleton/model/schema.json.twig
- src/Graviton/SchemaBundle/Document/Schema.php
- src/Graviton/SchemaBundle/Model/SchemaModel.php
- src/Graviton/SchemaBundle/Resources/config/schema/SchemaModel.json
- src/Graviton/SchemaBundle/Resources/config/serializer/Document.Schema.xml
- src/Graviton/SchemaBundle/SchemaUtils.php
This pull request adds a `readOnly` property to the item schema as [defined in JSON Schema v4](http://json-schema.org/latest/json-schema-hypermedia.html#anchor15). So the schema of all fields, which are defined as readonly within the `Resources/config/schema/$Service.json`, will be extended by `"readOnly": true`.
> expose readonly fields as readonly

- src/Graviton/SchemaBundle/Resources/config/services.xml
- src/Graviton/SchemaBundle/SchemaUtils.php
- src/Graviton/SwaggerBundle/Service/Swagger.php
This fixes us not being able to ``composer update && dev-cleanstart.sh`` in wrappers by making all the triggered commands work without access to a database.
It also fixes running ``docker-compose run --rm install`` by making a simple ``composer install`` possible without needing a running mongodb.
The change it introduces is that only the default locale ``en`` will be documented in swagger from here on out.
Schema endpoints (``/schema/*/item`` and ``/schema/*/collection``) are not affected.
This doesn't fix the underlying issues I'm seeing in wrappers after a ``composer update`` that probably pertain to ``doctrine/*`` stuff.
> Generate swagger without relying on mongodb

- src/Graviton/CoreBundle/Resources/definition/Config.json
We do have some global config that we want to add.
I'm fully aware that this now exposes the silly ``app: {}`` artefact everywhere. We'll just have to live with that for the time being...
Also, this is for [EVO-443](https://issue.swisscom.ch/browse/EVO-443)...
> Make app.$ref in /core/config optional

- .travis.yml
- composer.json
- composer.lock
PHP-5.4 is EOL and does not get and more security updates. Hence we stop supporting it.
> Get rid of obsolete php-5.4 support

- src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
- src/Graviton/DocumentBundle/Listener/ExtReferenceSearchListener.php
- src/Graviton/DocumentBundle/Tests/Listener/ExtReferenceSearchListenerTest.php
RQL query visitor is not able to make proper MongoDb queries with logical operators because it doesnt pass current `Expr` context for operands.
Now we dont use `Builder` in `ExtReferenceSearchListener` and just replace node with correct field name and `extref` in DB format.
> 590 fix searching by extref

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php
- src/Graviton/RestBundle/Model/DocumentModel.php
- src/Graviton/RestBundle/Resources/config/services.xml
The `Link` header contents regarding pagination are currently wrong
* It still checked for the GET param `page` to determine the page - this leads to correct headers, but the `prev` part is missing and `last` is rendered on the last page (as it's always assuming we are on page `1`).
I reflected the new correct behavior in `AppControllerTest` - it was not checked for the `prev` part there..
Additionally, I added a new header `X-Total-Count` returning the total number of records. Clients asked for this and it doesn't hurt to add it (the total count from mongo was already fetched to determine the number of pages). I got the name of the header from [here](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pagination), a [google …
> fix pagination, add X-Total-Count header

- src/Graviton/FileBundle/Resources/definition/File.json
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
this one fixes EVO-444 - we add a new array of possible "action.commands" strings to `/file` - this is for worker logic on files.
it needs to be an array as specified - and as we cannot generate a bag of primitives `[string, string, string]`, we need to generate an array of objects - the key is `command`. so it would be `action: [ { command: 'print' } ]`
> new action array on /file metadata

- composer.lock
I ran composer update for my work on EVO-705 after noticing outdated lockfile warnings on develop and was not willing to throw the work away.
Test still run and I don't believe this pulls any deps that hurt.
> Bump various dependencies

- .travis.yml
- app/config/config_dev.yml
- app/config/config_test.yml
- app/config/deploy.yml.dist
- phpunit.xml.dist
This contains 2 things:
* make doubly sure that airbrake doesn't want to report anything on dev and test or when it is ignored in config
* parallelize stuff on travis so we get results faster
This doesn't outright make our tests fast, but it does improve the time to first result quite a bit.
Most importantly if fixes a an issue that started when the airbrake lib started seeing ``""`` as valid api key. That was certainly not the intended behaviour since it spewed heaps of messages when I tried to run it locally.
I also parallelized large parts of our travis builds. After the travis refactor, I pushed https://github.com/libgraviton/graviton/commit/0685db10489c8f6a484844f363aa6c9605597b65 on another branch to validate that we still [fail on …
> Some test fixing

- src/Graviton/CoreBundle/Resources/config/routing.xml
- src/Graviton/RestBundle/Routing/Loader/ActionUtils.php
- src/Graviton/RestBundle/Service/RestUtils.php
The _method thingy was deprecated many moons ago as per [symfony/symfony/UPGRADE-3.0.md](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#routing).
This should help overall performance due to much less log entries getting written... There are still heaps remaining though.
> Use setMethods() instead of '_method' requirement

- app/config/parameters.yml.dist
- composer.json
- composer.lock
- src/Graviton/CoreBundle/Compiler/VersionCompilerPass.php
We need to override this on cloudfoundry so it uses the buildpacks composer installation by setting it to `php /tmp/staged/app/php/bin/composer.phar`.
This should make graviton deploy again after #260 broke it, but I'm having a hard time testing it due to most likely unrelated errors when pushing to my own instances :/
> Allow configuration of composer command path

- src/Graviton/CoreBundle/Compiler/VersionCompilerPass.php
Given a multi part `composerCmd` we were calling `cd '/path/to/root'/../ && 'php composer.phar' show ...`. But we need to have the multi-part `composerCmd` with a bit less escaping if we want this not to bomb.
> Fix escaping of args and cmd

- src/Graviton/DocumentBundle/Listener/ExtReferenceListener.php
- src/Graviton/GeneratorBundle/Definition/JsonDefinitionField.php
- src/Graviton/GeneratorBundle/Definition/Schema/Field.php
- src/Graviton/GeneratorBundle/Definition/Schema/XDynamicKey.php
- src/Graviton/GeneratorBundle/Resources/config/serializer/Definition.Schema.Field.xml
- src/Graviton/GeneratorBundle/Resources/config/serializer/Definition.Schema.XDynamicKey.xml
- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.php.twig
- src/Graviton/GeneratorBundle/Resources/skeleton/model/schema.json.twig
- src/Graviton/GeneratorBundle/Tests/Definition/BaseJsonDefinitionFieldTest.php
- src/Graviton/GeneratorBundle/Tests/Definition/DefinitionElementTest.php
- src/Graviton/GeneratorBundle/Tests/Definition/JsonDefinitionFieldTest.php
- src/Graviton/SchemaBundle/Document/Schema.php
- src/Graviton/SchemaBundle/Model/SchemaModel.php
- src/Graviton/SchemaBundle/Resources/config/schema/SchemaModel.json
- src/Graviton/SchemaBundle/Resources/config/serializer/Document.Schema.xml
- src/Graviton/SchemaBundle/Resources/config/services.xml
- src/Graviton/SchemaBundle/SchemaUtils.php
- src/Graviton/SchemaBundle/Service/RepositoryFactory.php
- src/Graviton/SchemaBundle/Tests/Service/RepositoryFactoryTest.php
This make it able to express that we need to expose an array as an object while using parts of the object as key. This takes part of schema and service output, making such stuff writable still needs taking care of.
Given the following (simplified) field definition:
```js
{
"name": "field",
"type": "class:AcmeBundle\\Document\\Field",
"x-dynamic-key": {
"document-id": "GravitonDynModuleBundle:Module",
"repository-method": "findAll",
"ref-method": "getRef"
}
}
```
The schema it generates should contain a property for every record id from the result set of `GravitonDynModuleBundle:Module::findAll`.
The swagger-schema shall contain an `additionalProperties` property allowing any id to be used.
It should generate a `Document` class that returns the value of `field` as an associative array …
> Dynamic key support in schemas and output

- src/Graviton/GeneratorBundle/Definition/JsonDefinition.php
- src/Graviton/GeneratorBundle/Definition/Schema/Service.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
- src/Graviton/GeneratorBundle/Resources/config/serializer/Definition.Schema.Service.xml
- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig
This allows us to define what collection a service takes its data from. This can be used if the same data need to be presented differently depending on the endpoint.
I plan on using it to keep an editable version of a service containing some dynamic keys available at a different path. While it won't be used in that way as soon as dynamic keys are writable I still think this might have it's merits later on.
It can also be used if we want to reference something from an existing collection in a readonly service so there's that as well.
Look no further than [here](https://git.swisscom.ch/projects/GRV/repos/graviton-evojachecklistbundle/pull-requests/1/overview) for where I want to use this (and while you're there, that one would like to get merged as well :pray:).
> Allow defining of mongo db collection a service maps to

- src/Graviton/RestBundle/Listener/SelfLinkResponseListener.php
currently, if the user issues a POST to `/file` (no slash at the end), the Self Link header (and thus the `EventStatus` documentUrl that depends on that) wrongly point to a *collection* (`?id=xxx`) instead to a single resource (`/file/<id>`).
This PR fixes that behavior
> correctly generate _self Link header part to a single resource on postNoSlash route type

- composer.json
- composer.lock
This brings us in line with how composer recommends to use this.
The version was previously used by the X-Version header which has now been replaced with the `/core/version/ service.
This make tagging graviton releases easier since no more hacking of composer files is needed anymore.
> Remove version from compoer.json

- src/Graviton/RestBundle/Listener/SelfLinkResponseListener.php
- src/Graviton/RestBundle/Model/DocumentModel.php
currently, if the amount of data of the *first* page of a response exceeds the "default pagination setting", we generate a wrong _self link header part as it's still "perPage" and "page" in there..
this can be demonstrated using curl in our develop instance (as long it will be not deployed) as we have more than 10 customers in there:
```bash
curl -vv 'http://evoja-szkb-bap-backend-develop.nova.scapp.io/person/customer/'
Link: <http://evoja-szkb-bap-backend-develop.nova.scapp.io/person/customer/?limit(10%2C10)>; rel="next",<http://evoja-szkb-bap-backend-develop.nova.scapp.io/person/customer/?limit(10%2C30)>; rel="last",<http://evoja-szkb-bap-backend-develop.nova.scapp.io/person/customer/?page=1&perPage=10>; rel="self"
```
please note the part …
> fix correct _self link header part when request exceeds defaut pagelimit and no rql has been given..

- src/Graviton/CoreBundle/Resources/config/routing.xml
changes in the /core/version service introduced some deprecation warnings in the logs..
```
[2015-10-14 08:27:16] php.INFO: The "_method" requirement of route "graviton.core.static.version.get" in file "/home/dn/git/graviton2/src/Graviton/CoreBundle/Resources/config/routing.xml" is deprecated since version 2.2 and will be removed in 3.0. Use the "methods" attribute instead. {"type":16384,"file":"/home/dn/git
```
this PR changes the definition to the newer method..
> fix method requirement in version routing

- composer.json
- composer.lock
just something i've seen.. is this useful for anything? maybe an old cloud workaround? i think `/app/htdocs` does not exist anywhere, not even in the cloud (it's `/app/app/src`).. so can remove?
> remove autoloader wtf

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/RestBundle/Routing/Loader/ActionUtils.php
- src/Graviton/RestBundle/Routing/Loader/BasicLoader.php
i know, we all didn't want to support HEAD requests in the first place ;-/
but as it turns out, some browsers make them and there is no way to disable that.
Graviton currently handles them in a rather inconsistent way - it answers it with an 2** status code, but actually processes the data request in `allAction()` in `RestController` but then has an empty response body. I've seen that it gets data by the delayed answer, the presence of the `x-total-count` header in the response and dev.log output.
this PR handles HEAD the same as we handle OPTIONS. this suffices as the only thing the client (m$ie) is looking for in the HEAD response is the presence of a `Content-Type` header (afaik), which we provide in the OPTIONS request.
> fix HEAD handling

- src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php
- src/Graviton/RabbitMqBundle/Tests/Listener/EventStatusLinkResponseListenerTest.php
I've just seen that Graviton generated me an `EventStatus` resource on an `OPTIONS` request. that is obviously a wrong behavior..
So I cleaned up the messy part in `isNotConcerningRequest()` in the `EventStatusLinkResponseListener`  - this was prone to wrong behavior. It's way better to just see if we have a routing key - which can only be done if the current request has been mapped by our `CompilerPass`. this way, we have a whitelist approach as opposed to the blacklist based on before..
I also made sure we only go forward if we have an eventName in the `QueueEvent`. This always needs to be the case..
> change the way we determine if it's a concerning request for EventStatus

- src/Graviton/RestBundle/Listener/SelfLinkResponseListener.php
at the moment we see this in dev.log:
```
php.INFO: The Symfony\Component\EventDispatcher\Event::getDispatcher method is deprecated since version 2.4 and will be removed in 3.0. The event dispatcher instance can be received in the listener call instead.
```
this PR makes us use the dispatcher the 'new' way..
> fix symfony deprecation warning getDispatcher()

- app/AppKernel.php
- app/bootstrap.tests.php
- app/config/config.yml
- composer.lock
- phpunit.xml.dist
- src/Graviton/I18nBundle/Event/TranslatablePersistEvent.php
- src/Graviton/I18nBundle/Listener/I18nCachingListener.php
- src/Graviton/I18nBundle/Listener/PostPersistTranslatableListener.php
- src/Graviton/I18nBundle/Resources/config/services.xml
- src/Graviton/I18nBundle/Service/I18nCacheUtils.php
- src/Graviton/I18nBundle/Tests/Controller/ExternalTranslationDomainControllerTest.php
- src/Graviton/I18nBundle/Tests/Service/I18nCacheUtilsTest.php
- src/Graviton/I18nBundle/Translator/Translator.php
this tries to solve the translation problems we observed mostly in the cloud. but it worked mostly locally.
**why did it not work in the cloud?**
at container build time, the translator resource files in the bundles that trigger the load (like `core.de.odm`) are searched and put as a *fixed* list in the *compiled* container.
as we added translations for new domains, they were never loaded as those files were never present at container build time. 
**why did it work locally (mostly)?**
locally, after we created some domains, it also created the trigger file (like `hans.de.odm`). as we develop, we often run a script like `dev-cleanstart.sh` - which rebuilds the container among other things. once we did that, translations for that domain did work.
so -> it never worked in the cloud because …
> EVO-949 - fix translation of non-existant translation domains at container build time

- composer.json
- composer.lock
- src/Graviton/CoreBundle/Tests/Controller/ElemMatchOperatorControllerTest.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/ExtRefFieldsCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/RqlFieldsCompilerPass.php
- src/Graviton/DocumentBundle/GravitonDocumentBundle.php
- src/Graviton/DocumentBundle/Listener/ExtReferenceSearchListener.php
- src/Graviton/DocumentBundle/Listener/FieldNameSearchListener.php
- src/Graviton/DocumentBundle/Resources/config/services.xml
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/ExtRefFieldsCompilerPassTest.php
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/RqlFieldsCompilerPassTest.php
- src/Graviton/DocumentBundle/Tests/Listener/ExtReferenceSearchListenerTest.php
- src/Graviton/DocumentBundle/Tests/Listener/FieldNameSearchListenerTest.php
- src/Graviton/GeneratorBundle/Definition/JsonDefinitionHash.php
- src/Graviton/GeneratorBundle/Tests/Definition/DefinitionTest.php
This is a part of [EVO-623](https://issue.swisscom.ch/browse/EVO-623). This is needed for searching files by links using `elemMatch()` RQL operator:
* Added new functional test
* Added `RqlFieldsCompilerPass` to save `rql field <=> database field` mapping
* Added `FieldNameSearchListener` to map RQL field names to correct database names
* Fixed a small bug in JSON definition parsing
This depends on the following changes:
I will remove aliases from `composer.json` when they will be merged.
> 47970 add elemmatch operator

- src/Graviton/FileBundle/Controller/FileController.php
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
no service in Graviton returns a `Location` header on a `PUT` request. but `/file` does. this PR makes `/file` behave as any other service in this regard.
some clients wrongly try to follow present `Location` headers in all methods except `POST` - sending this will lead a browser like Chrome to try to make OPTIONS preflight request and/or directly GET the file - this is not what we want, especially with a service like `/file` that potentially serves big objects..
> make PUT on /file *not* return a Location header

- src/Graviton/FileBundle/Controller/FileController.php
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
fixes bug that _self link does not contain the id of the added document.
> Added missing file id to request

- .bp-config/options.json
this is needed to push vanilla graviton again, as the 'NGINX_17_LATEST' thingy is outdated in the php buildpack..
> fix vanilla graviton deploy

- src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
- src/Graviton/DocumentBundle/Entity/ExtReference.php
- src/Graviton/DocumentBundle/GravitonDocumentBundle.php
- src/Graviton/DocumentBundle/Types/HashType.php
so.. this one adds the ability to save and display extrefs inside hashes ('free form objects')
obviously, we have no idea where they can be.. so we need to recurse that hash..
**what it does**
* recurse the hash (**important:** remember, that we *only* recurse the current hash! so in a big service like *consultation*, only a subset of objects are hashes - and there, we iterate that one smaller subhash)
* if we find an `$ref` field, transform it to a mongodb ref and save it like that under a new name (it needs to be a new name as `$ref` would need an `$id` field on the *same level!*)
* on output, transform it back to `$ref` - we can spot our fields by the unique keyword fieldname
* for all extref stuff, we use the in-place `ExtRefConverter`
**drawbacks**
remember: this is a workaround. …
> fix extref in hash

- src/Graviton/CoreBundle/Resources/config/routing.xml
- src/Graviton/CoreBundle/Resources/config/services.xml
- src/Graviton/CoreBundle/Tests/Controller/VersionControllerTest.php
as said.. /core/version should be /core/version/ (with trailing slash) so it's consistent with all other services)
> EVO-1281 - make /core/version urls the same as all others (having / at the end)

- src/Graviton/CoreBundle/Service/CoreVersionUtils.php
- src/Graviton/CoreBundle/Tests/Controller/VersionControllerTest.php
- src/Graviton/CoreBundle/Tests/Services/CoreVersionUtilsTest.php
The core/version service returns the wrong version of the root package ('self'). We are reading the self-version out of a composer show command. Since there is no ('handwritten') version tag in the composer.json file anymore, composer gets the information from somewhere else. Composer adds a 4th version after the patch version for a reason that i could not figure out. Nevertheless, this 4th identifier adds no further information and is not SemVer-valid, so it has to be removed.
> Wrong self-version in core/version

- src/Graviton/CoreBundle/Service/CoreVersionUtils.php
- src/Graviton/CoreBundle/Tests/Services/CoreVersionUtilsTest.php
The string normalizer implemented in #326 should only cut strings with 4 version parts. Version strings like "No version set (parsed as 1.0.0)" should be ignored.
> EVO-1280: fix normalizing strings

- src/Graviton/CoreBundle/Resources/config/routing.xml
- src/Graviton/CoreBundle/Resources/config/services.xml
- src/Graviton/CoreBundle/Tests/Controller/VersionControllerTest.php
As it has been stated in #325, `/core/version` is indeed a resource, not a collection, so it should not have a trailing slash..
Was a mistake on my side, let's revert my changes
> Revert /core/version changes introduced in #325

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
- src/Graviton/I18nBundle/Tests/Controller/TranslatableControllerTest.php
- src/Graviton/RestBundle/Controller/RestController.php
This adds `PATCH` method to `Access-Control-Allow-Methods` header to prevent the error `XMLHttpRequest cannot load https://<url>. Method PATCH is not allowed by Access-Control-Allow-Methods` with enabled CORS checking.
> EVO-1389 Add PATCH method to "Access-Control-Allow-Methods" header

- src/Graviton/MigrationBundle/Command/MongodbMigrateCommand.php
The command fails miserably when it gets passed a path that does not start with /.
> Use full path when calling command

- src/Graviton/CoreBundle/Resources/config/doctrine/App.mongodb.xml
- src/Graviton/CoreBundle/Resources/config/doctrine/Product.mongodb.xml
- src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig
i took a look at EVO-1782. this led me first to believe it's not that trivial.
after digging deeper and creating [this issue on the mongo-odm project](https://github.com/doctrine/mongodb-odm/issues/1294), it seems that there is an easy fix in our context.
as it turns out, we *wrongly* specify `type='string'` on identifier fields. this makes `mongo-odm` to use the `StringType` instead of the `CustomidType` what would be used otherwise and *also results in a string based ID in MongoDB*.
This is important as `StringType` casts everything to `string` (obviously) for ID based searches - `CustomidType` doesn't do that, it preserves the `\MongoRegex` instance.
So, removing `type='string'` from our generated services indeed allows the user to issue `like()` RQL expression on the `id` field! And …
> fixe like() searches on identifier fields

- app/AppKernel.php
- app/config/config.yml
- composer.json
- composer.lock
- src/Graviton/MigrationBundle/Command/Helper/DocumentManager.php
- src/Graviton/MigrationBundle/Command/MongodbMigrateCommand.php
- src/Graviton/MigrationBundle/Resources/config/services.xml
This replaced the bundle with some code under our own control. For the most part I needed to do this since it was rather hard to override some of the internals of the commands in the bundle.
This PR uses the symfony dic to configure the *raw* command from antimattr/mongodb-migrations in the simplest possible fashion. When calling the commands using ``graviton:mongodb:migrate`` it injects the needed config as a helper and makes sure to do so early enough.
> Remove antimattr/mongodb-migrations-bundle

- .travis.yml
This is so we can get ready for php7. Before supporting php7 as a deploy target we still need to wait on ext-mongodb (and thus on doctrine/mongodb and doctrine/mongodb-odm).
By using mongofill we can ensure we don't break php7 stuff in any unrelated places while waiting for that.
> Fix mongofill install and remove php7 from allowed failures

- composer.json
- composer.lock
- src/Graviton/CoreBundle/Tests/Controller/DatetimeDeserializationControllerTest.php
- src/Graviton/DocumentBundle/Form/Type/FieldBuilder/DateArrayFieldBuilder.php
- src/Graviton/DocumentBundle/Form/Type/FieldBuilder/DateFieldBuilder.php
- src/Graviton/DocumentBundle/Tests/Form/Type/FieldBuilder/DateArrayFieldBuilderTest.php
- src/Graviton/DocumentBundle/Tests/Form/Type/FieldBuilder/DateFieldBuilderTest.php
- src/Graviton/RestBundle/Validator/Constraints/ReadOnly/ReadOnlyValidator.php
This fixes the input format of date fields (see http://symfony.com/doc/current/reference/forms/types/datetime.html#input).
Current implementation returns date values as strings in `$form->getData()`.
Such behavior doesn't allow to implement services like calculators, where we have to respond immediately with given data.
I added the new test. Without my changes the test throws the exception:
```
DatetimeDeserializationTestController.php on line 41:
Graviton\ExceptionBundle\Exception\SerializationException {#2283
-statusCode: 500
-headers: []
#message: """
exception 'JMS\Serializer\Exception\LogicException' with message 'Expected object but got string. Do you have the wrong @Type mapping or could this be a Doctrine many-to-many relation?' in …
```
> EVO-1383 fix datetime deserialization

- src/Graviton/FileBundle/FileManager.php
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
This PR brings the functionality of `PUT`ting new files with custom `id`s back to the file service. Moreover, it adds a test which ensures that this feature doesn't get lost anymore.
> Bring back upsert with custom id for file service

- src/Graviton/FileBundle/Controller/FileController.php
- src/Graviton/FileBundle/FileManager.php
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
This PR does the following:
* fix a bug where the `metadata.filename` of a file does not get set to the filename provided in the `metadata` filed on `multipart/form-data` requests
* extends a test for the above case
* refactors the `FileManager`
> Fix filename multipart/form-data bug, refactor FileManager

- src/Graviton/FileBundle/FileDocumentFactory.php
- src/Graviton/FileBundle/Resources/definition/File.json
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
With this PR we add an additional key/value store named additionalProperties to the metadata.
We need this new field, because we want print and archive PDF and other files. Our printing and archive system needs more information about which printer must be used and where can the file be stored for example.
> add additional field to the file service

- src/Graviton/DocumentBundle/DependencyInjection/GravitonDocumentExtension.php
They are only interpreted as json if they start with either `{` or `[` as to not disturb the old behaviour where they where but simple strings.
> Allow injected SYMFONY__ envs to contain json

- src/Graviton/CoreBundle/Compiler/EnvParametersCompilerPass.php
- src/Graviton/CoreBundle/GravitonCoreBundle.php
- src/Graviton/CoreBundle/Tests/DependencyInjection/CompilerPass/EnvParametersCompilerPassTest.php
- src/Graviton/DocumentBundle/DependencyInjection/GravitonDocumentExtension.php
as mentioned in #357, we still have a major problem how to set params from `ENV` for docker based stuff during runtime.
*important:* we could override params before via `SYMFONY__` envs. but as soon as it concerns params that are referenced in a DIC definition (`%paramname%` in xml), this will not work. this concerns investment bundle stuff as also stuff in `SecurityBundle`.
this approach tries to solve it by:
* assume that we deploy the application without an existing compiled container (no `/app/cache/<env>`)
* once the app is running (with `ENV` set via recipe or any other way), the `CompilerPass` will write it to the `Container` - this time, they will land in the then compiled container.
the main point of this is that we must ensure the cache is built on runtime by not deploying a …
> env params via compiler pass

- src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
- src/Graviton/CoreBundle/Tests/Controller/TranslatableRequiredTest.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentFormFieldsCompilerPass.php
- src/Graviton/DocumentBundle/Form/Type/FieldBuilder/TranslatableFieldBuilder.php
- src/Graviton/DocumentBundle/Resources/config/services.xml
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/DocumentFormFieldsCompilerPassTest.php
Graviton behaves wrongly when a service has a `translatable` that is **not** `required: true`. 
If the user omits it from the request, Graviton falsely complains with `[{"propertyPath":"children[field]","message":"This value is not valid."}]` and HTTP status `400`.
This PR fixes this.. I created this to replace #361 as it was quite cluttered..
*Why was ShowcaseControllerTest modified?*
That's a good question indeed.. In `ShowCase.json` we have `someOtherField`, an optional Translatable. And still, our ShowCaseControllerTest expected Graviton to complain when you omit this optional Translatable. So it tested wrong behavior. I removed this now..
*Required behavior*
If a translatable is not required, it shall not be required.
> fix optional translatables

- src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php
If you check this -> http://api.dev-pub.zgkb.evoja.ch/event/status/?eq(eventName,document.financingcollateraltype.financingcollateraltype.update)
You'll see many `/event/status/` objects that *should not* exist. So I fiddled around with MongoRegex on the shell - and it turns out that I made a mistake in the current implementation. We need to search with a subexpression, not with a character class.
> lookup subscribed workers with subexpression, not character class

- app/config/parameters.yml.dist
- src/Graviton/CoreBundle/Listener/RequestHostListener.php
- src/Graviton/CoreBundle/Resources/config/services.xml
Graviton rightfully doesn't care what urls it generates (like `extref`s or self urls).. As long as it's resolvable by `Router` and the request actually hits us, we are fine..
In all future scenarios, Graviton will be proxyed by some component. Be it something like Tyk or Kong or some L-Backend - some component will be in front. This arises the need of content rewriting in the JSON. 
At our first client, it seems it goes to a point where we'll put L-Backend (a shrinked version of it only containing the `ProxyBundle` and `/api/auth`) on the same host as Graviton (= meaning same hostname). 
Under that scenario it would be optimal if Graviton generates the URL from the L-Backend - and as they are on the same host and L-Backend proxies the request) - no content and/or content rewriting is …
> introduce means to change rendered urls by configuration

- src/Graviton/I18nBundle/Resources/config/doctrine/Translatable.mongodb.xml
- src/Graviton/I18nBundle/Service/I18nUtils.php
- src/Graviton/I18nBundle/Tests/Controller/LanguageControllerTest.php
Fixes [EVO-2923](https://issue.swisscom.ch/browse/EVO-2923) by storing the domain in the id properly. 
I also had to rewrite a translatable controller test so it works more like the actual reading of translatables.
> Fix storing of language string for different domains

- src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php
- src/Graviton/RabbitMqBundle/Resources/config/services.xml
- src/Graviton/RabbitMqBundle/Resources/definition/EventStatus.json
- src/Graviton/RabbitMqBundle/Tests/Listener/EventStatusLinkResponseListenerTest.php
In talks it has been discussed that it would be nice to enable the user to lookup certain events by the originating REST resource that created a certain `/event/status`.
So this PR adds a `$ref` to every `/event/status/` record. It points to the exact document that was created/updated and allows for more precise RQL searches to find relevant status entries.
I also added more testing so the object that the `Listener` persists gets inspected more in detail.
> EVO-2938 - add ref to event status

- src/Graviton/GeneratorBundle/Tests/Definition/JsonDefinitionArrayTest.php
- src/Graviton/ProxyBundle/Controller/ProxyController.php
- src/Graviton/ProxyBundle/Definition/ApiDefinition.php
- src/Graviton/ProxyBundle/Definition/Loader/DispersalStrategy/SwaggerStrategy.php
- src/Graviton/ProxyBundle/DependencyInjection/Configuration.php
- src/Graviton/ProxyBundle/README.md
- src/Graviton/ProxyBundle/Service/ApiDefinitionLoader.php
- src/Graviton/ProxyBundle/Tests/Definition/ApiDefinitionTest.php
- src/Graviton/RestBundle/Service/JsonPatchValidator.php
This PR adds a configuration which defines whether graviton should expose thirdparty endpoints with or without the thirdparty API's base path. Since exposing this base path does not make sense in most cases, the default behavior is removing it.
In addition, the following fixes are applied:
1. On `/3rdparty/{prefix}/{endpoint}` requests, use the thirdparty API defined by the prefix in the URL or throw a `NotFoundException` when no such prefix is defined (current behavior is always using the last configured thirdparty API by completely ignoring the prefix in the URL)
2. Path normalization (removing one path `{parameter}` at the end of the path for the endpoint overview) for swagger sources is removed (as discussed with @samsamann). Reason: Removing the `{parameters}` at the end of the …
> EVO-2891: Add a ProxyBundle configuration for including / excluding the base path of thirdparty APIs

- src/Graviton/I18nBundle/Migrations/MongoDB/Version20160303110805.php
- src/Graviton/I18nBundle/Resources/config/migrations.yml
I prepared this so it will work in wrappers and you need to do some small changes if you want to test it without cloning it in a wrappe (as noted in migrations.yml). We should not really need this on bare graviton deploys anyhow since those are not getting a lot of action and have way less potential for conflicts.
I created a test branch on an internal wrapper to demonstrate how this works... Hit me up if you can't find it.
> Simple migration for translatable index

- src/Graviton/RestBundle/Listener/CorsResponseListener.php
- src/Graviton/RestBundle/Resources/config/services.xml
I'm moving the Access-Control-Allow-Headers to the DIC for consistency. I'm also allowing the X-REST-Token header since most clients are sending that due to how they implemented against legacy.
This is a fix for some issues we are seeing on rel-pub...
> Fix cors headers for mock auth

- app/config/config_dev.yml
- app/config/config_prod.yml
- app/config/parameters.yml.dist
- composer.json
- composer.lock
We want to expose the log file destination for our Docker CD infrastructure..
Once tagged, I'll open PRs for the wrappers..
I tested this locally with a branch on a wrapper - setting the parameter to `php://stdout` indeed makes `ERROR`s pop up on the stdout of the `*-backend` docker container using `docker logs`
I guess we leave the loglevel on `error` on `prod` environment?
> flexibilize monolog log destination via incenteev

- app/AppKernel.php
- app/config/config_test.yml
This starts doing what #378 tried to do as well. The two changes have been tried locally numerous times and they each make the integration testsuite several minutes faster.
Let me know if you know any other optimizations that might help. I'm still looking for a way to make fixture loading faster for one.
> Optimize tests

- composer.json
- composer.lock
You may see the following messages from composer:
```
Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.
Package oldsound/rabbitmq-bundle is abandoned, you should avoid using it. No replacement was suggested.
```
User `videlalvaro` has moved his projects to the `php-amqplib` organization and other maintainers took over. So we shall change our dependencies accordingly..
This *may* conflict with #383 (`composer.lock` changes) upon merge of either one, see what comes first..
> update to new php-amqplib & bundle

- src/Graviton/CoreBundle/Resources/config/routing.xml
- src/Graviton/RestBundle/Service/RestUtils.php
Currently, beco has this error when it tries to load `/core/version` via XHR (a.k.a "ajax") as the browser makes a preflight `OPTIONS`:
```
XMLHttpRequest cannot load http://api.dev-pub.szkb.evoja.ch/core/version. Response for preflight has invalid HTTP status code 405
```
This is, because somebody forgot to add `OPTIONS` method to `/core/version` - here we add it ;-)
> add OPTIONS to /core/version and its schema

- src/Graviton/RestBundle/Resources/config/services.xml
Due to the ALIDA auth a new header is needed. This will be later replaced with oauth2.
> ALIDA auth header

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/RestBundle/Controller/RestController.php
changed the returned http status for options requests to 204 to preve…nt browser from caching cors preflights
> http 200 causes cors preflights to cache content

- src/Graviton/RabbitMqBundle/Resources/config/services.xml
for EVO-5106..
adds a new possible value for `status.status` in `/event/status`. The new `ignored` status shall be set by a worker if he decides to not do anything on a given work item, as opposed to just set it to `done`. The status `done` without having actually done anything is misleading, we need to be able to distinguish that case.
> add new 'ignored' status to /event/status worker status

- composer.json
- composer.lock
- phpunit.xml.dist
- src/Graviton/CoreBundle/Controller/MainController.php
- src/Graviton/CoreBundle/Resources/config/services.xml
- src/Graviton/CoreBundle/Tests/Controller/MainControllerTest.php
- src/Graviton/DocumentBundle/Service/ExtReferenceConverter.php
- src/Graviton/FileBundle/Resources/config/services.xml
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
- src/Graviton/I18nBundle/Resources/config/services.xml
- src/Graviton/PersonBundle/Resources/config/services.xml
- src/Graviton/RestBundle/Listener/SelfLinkResponseListener.php
- src/Graviton/SchemaBundle/Listener/CanonicalSchemaLinkResponseListener.php
- src/Graviton/SchemaBundle/Listener/SchemaContentTypeResponseListener.php
- src/Graviton/SchemaBundle/SchemaUtils.php
- src/Graviton/SecurityBundle/Resources/config/services.xml
- src/Graviton/TestBundle/Resources/config/services.xml
This gets rid of some deprecation warning by doing the following.
* update calls to `router->generate` to use constant based argument
* rewrite factory service configuration to the `<factory>` tag style
* dropping faker from production requirements since it should not be there and does not see any use
* install `symfony/phpunit-bridge` to aid future development
There are still more deprecated things going on but I prefer not to bloat this PR. Maybe we'll be able to remove `SYMFONY_DEPRECATIONS_HELPER=weak` after having fixed more stuff at a later stage.
> Spring cleaning :D

- src/Graviton/CoreBundle/Resources/definition/Config.json
- src/Graviton/GeneratorBundle/Definition/JsonDefinition.php
- src/Graviton/GeneratorBundle/Definition/Schema/Target.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
- src/Graviton/GeneratorBundle/Resources/config/serializer/Definition.Schema.Target.xml
- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig
- src/Graviton/GeneratorBundle/Tests/Definition/DefinitionTest.php
This was done as part of [EVO-5196](https://issue.swisscom.ch/browse/EVO-5196) and gets us half the way there. IMHO these changes should have been implemented quite some time ago.
I need work on this issue some more for it to add all the search fields. Those changes will need proper checking of all downstream use-case if we want to realize it properly.
> Add indexes as defined in target.indexes to doctrine mapping

- src/Graviton/I18nBundle/Command/CreateTranslationResourcesCommand.php
- src/Graviton/I18nBundle/Resources/config/services.xml
- src/Graviton/I18nBundle/Tests/Command/CreateTranslationResourcesCommandTest.php
This should fix the issue of losing translations during redeploy on immutable infrastructure.
> Add command to initialize symfony/translation from mongodb

- composer.json
- composer.lock
https://github.com/libgraviton/php-rql-parser/releases/tag/v2.0.1
Removing Alpha use.
> RQL parser update to use dash in string values

- src/Graviton/I18nBundle/Command/LoadMissingCommand.php
I recently stumbled upon this and it's still itching. I don't think anyone is actually using the command so this change should not have an impact.
> Fix typo in name of command

- composer.lock
- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig
I updated to the new doctrine stuff in my branch and got this error message
```
[Doctrine\ODM\MongoDB\Mapping\MappingException]                                                                                              
Invalid strategy pushAll used in GravitonDyn\TestCaseTranslatableArrayBundle\Document\TestCaseTranslatableArray::array with type collection
```
And indeed, the `strategy` attribute should only be set on `embed-*` and `ref-*` fields, not others (surely not the primitives we do there). And there we already set it (to `set`).. so all dandy there.
This is only a problem when we want to update `doctrine/mongodb-odm` (what we should do), as 1.1.0 complains about this wrong definition.
So this updates the doctrine deps and fixes our xml definitions..
> fix doctrine strategy on primitives & update doctrine/* deps

- composer.json
- composer.lock
- src/Graviton/CoreBundle/Tests/Controller/MainControllerTest.php
- src/Graviton/DocumentBundle/Tests/Form/Type/DocumentTypeTest.php
- src/Graviton/GeneratorBundle/Command/GenerateBundleCommand.php
- src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php
- src/Graviton/GeneratorBundle/Command/GenerateResourceCommand.php
- src/Graviton/GeneratorBundle/Generator/BundleGenerator.php
- src/Graviton/GeneratorBundle/Generator/ResourceGenerator.php
- src/Graviton/GeneratorBundle/README.md
- src/Graviton/GeneratorBundle/Tests/Command/GenerateBundleCommandTest.php
- src/Graviton/GeneratorBundle/Tests/Command/GenerateDynamicBundleCommandTest.php
- src/Graviton/GeneratorBundle/Tests/CommandRunnerTest.php
- src/Graviton/GeneratorBundle/Tests/Generator/ResourceGenerator/FieldMapperTest.php
- src/Graviton/GeneratorBundle/Tests/Generator/ResourceGeneratorProxy.php
- src/Graviton/GeneratorBundle/Tests/Generator/ResourceGeneratorTest.php
- src/Graviton/I18nBundle/Tests/Command/CreateTranslationResourcesCommandTest.php
- src/Graviton/I18nBundle/Tests/Form/Type/TranslatableTypeTest.php
- src/Graviton/ProxyBundle/Tests/Definition/Loader/HttpLoaderTest.php
- src/Graviton/RestBundle/Tests/Listener/XVersionResponseListenerTest.php
The phpunit was split out of @narcoticfresh's work in #430 to make that more lean and I'll take care of merging it there when we get this to develop. I realized that the time is ready to bump sensio/generator-bundle while I was looking into this and was able to bodge our code to conform to what the new bundle gives us. I haven't been able to get https://github.com/sensiolabs/SensioGeneratorBundle/pull/497 merged which would have also taken care of the remaining warnings left after this hack.
To test this in a graviton based wrapper you will need to update this in a fashion similar to the incantation `composer update graviton/* phpunit/* sensio/*` so it does not pull unwanted changes.
> Update phpunit and sensio/generator-bundle

- src/Graviton/GeneratorBundle/CommandRunner.php
I had quite some issues with getting the stuff in the feature/other-validation branch due to me having multiple php installs.
This uses an approach similar to what `Symfony\Component\Process\PhpProcess` does to figure out what executable to use.
It also wraps the call in exec as needed so signal properly reach the spawned commands.
> Use PhpExecutableFinder to run php commands

- src/Graviton/CoreBundle/Service/CoreVersionUtils.php
- src/Graviton/RestBundle/Model/DocumentModel.php
When using RQL param ?search we generate a new Query to remove the "search" string and build a unique TEXT. The limit resulted could be null and resulted in a exception, this would not happen in real as there is always present a limit in each rql request. This just fix this in case search is done without a limit and uses therefore the default value.
> Fixes a limit issue in search with Rql

- composer.json
- composer.lock
Done in here to be sure that downstreams get it applied as well.
I'm after [this](http://symfony.com/blog/cve-2016-2403-unauthorized-access-on-a-misconfigured-ldap-server-when-using-an-empty-password) since ldap is probably not off the table.
> Security bump for symfony

- src/Graviton/CoreBundle/Controller/MainController.php
* this fixes the problem of showing the whoami service in the services list twice
the display of the services is done by the method determineServices who takes as argument an array that holds all routes of graviton & the adapter. The whoami route is additionally defined as "additionalRoute" in app/config.yml which leads to the doubled  display of it here.
> EVO-6336 ommit doubled service display

- .travis.yml
- phpunit.xml.dist
- src/Graviton/CoreBundle/Tests/Controller/ModuleControllerTest.php
- src/Graviton/RabbitMqBundle/Tests/Controller/EventStatusControllerTest.php
- src/Graviton/SchemaBundle/Tests/Controller/SchemaConstraintsTest.php
> Bump MongoDB on travis and enforce unit/integration test split

- src/Graviton/SchemaBundle/Constraint/Builder/DecimalConstraintBuilder.php
- src/Graviton/SchemaBundle/Tests/Controller/SchemaConstraintsTest.php
i prematurely limited the amount of characters for the 'decimal string' field.. now i've seen some cases with quite higher precision and our limitation should go.. i don't like to up and up the integer there everytime ;-)
i also added some more asserts to negative and plus (= signed) amounts there..
> remove the precision amount completely, add test for signing symbols

- src/Graviton/RestBundle/Model/DocumentModel.php
It looks like the db user can be limited to get the db indexes. So I have changed the code to actually check on doctrine schema metadata. Will make it a bit faster and avoid a check on db for something php already knows.
> EVO-6985 Error on get search indexes, permission denied for user.

- src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php
With this PR, Graviton will no longer create `/event/status/` objects if an error occurred during the request processing.
> EVO-6779: Prevent creating an event status object if an error occurred

- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php
regex there was too greedy, replacing everything.. also adding a small assertion for that..
i'll need a tag right asap after merging this..
> EVO-7046 - fix incorporation of rql queries into pagination Link header parts

- src/Graviton/SchemaBundle/Constraint/ConstraintUtils.php
- src/Graviton/SchemaBundle/Constraint/RecordOriginConstraint.php
- src/Graviton/SchemaBundle/Resources/config/services.xml
- src/Graviton/SchemaBundle/Tests/Controller/RecordOriginConstraintTest.php
triggered through EVO-6960, we found an error how the `RecordOriginConstraint` checks if a current record exists or not. Falsely, it assumed there will always be an ID in payload - but as `RestUtils` in its check, also `ConstraintUtils` must fall back to the `Request` attribute `id` to make sure. Actually, the `Request` attribute is the one that must win.
We still have the check in place (in `RestUtils`) that will deny a request with a different id in payload and in the request URL..
This PR fixes the issue and adds an integration test to avoid regression..
> fix wrong id handling in recordorigin constraint

- src/Graviton/DocumentBundle/DependencyInjection/Compiler/RecordOriginExceptionFieldsCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/Utils/DocumentMap.php
This PR fixes a bug which prevented embeddedMany fields with `recordOriginException: true` from being modifiable.
Moreover, it fixes some wrong variable naming which got introduced by copy+paste...
> EVO-6960: Fix recordOriginException-embeddedMany-bug

- src/Graviton/CoreBundle/Tests/Controller/EmbeddingDocumentsTest.php
- src/Graviton/RestBundle/Model/DocumentModel.php
when we introduced 'new validation', we changed the `PUT` behavior that will not cascade deletes on referenced objects on the record to be updated.
But the issue still persists on `DELETE` request. Consider the following flow:
* User takes a /person/customer entity
* Changes `recordOrigin` to `hans` 
* `PUT`s it to /person/customer
* `DELETE`s it..
All referenced objects will be deleted in that case. In case of /person/customer, luckily this is only `CustomerGroup` at the moment (I observed missing `CustomerGroup`s on public instances and this may be the explanation).
But other services which my reference a `ConsultantLocation` or whatever will delete that `ConsultantLocation` - core data gets lost.
So we need to fix that..
> don't cascade deletes on DELETE

- src/Graviton/CacheBundle/Listener/ETagResponseListener.php
this is kinda urgent.. ;-)
it seems nginx is eating our `Etag` when compression is used (see EVO-7191, the comments there).. nginx stops doing this if we qualify our Etag as 'weak', indicated with the prefix of `W/`..
Small change big impact ;-)
> send weak etags to satisfy revers proxies like nginx

- app/AppKernel.php
- app/config/config.yml
- app/config/config_dev.yml
- app/config/config_test.yml
- composer.json
- composer.lock
It was never used and the only config I could find was there for deactivating it. This is most likely a remanence from the original symfony-standard-edition.
> Remove swiftmailer bundle

- composer.json
- composer.lock
- src/Graviton/RestBundle/GravitonRestBundle.php
- src/Graviton/RestBundle/Resources/config/services.xml
- src/Graviton/RestBundle/Tests/GravitonRestBundleTest.php
It seems to be quite some time ago when we stopped using this and reimplemented it natively in our MongoDB queries.
> Remove KnpPaginatorBundle

- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig
We use many embedded elements and on doctrine create schema it also copy those indexes over. This is not needed due to have the already option to added the specific needed index
> Remove indexes from embedded documents

- src/Graviton/CoreBundle/Resources/definition/ExternalLinks.json
a simple new extref field that allows to create groups of links by setting them the same type extref..
> EVO-7435 - add new field in external link service

- composer.json
- composer.lock
Version above do lead to array responses in some services where objects are expected.
checklist configuration. Wrappers do all have force 1.1.0 but the new ones should rely on Graviton.
> Forcing JMS serialiser to be at version 1.1.0 

- src/Graviton/CoreBundle/DataFixtures/MongoDB/LoadAppDataExceedSinglePageLimit.php
- src/Graviton/CoreBundle/Tests/Controller/AppControllerTest.php
- src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php
we currently generate wrong paging headers if the user doesn't pass any rql *but* we have more than the default pagesize in the database..
we generate:
```
Link: <https://host/person/customer/?&limit(10%2C10)>; rel="next",<https://host/?&limit(10%2C170)>; rel="last",<https://host/person/customer/?limit(0%2C10)>; rel="self"
```
and `?&limit` makes the url invalid.. this PR corrects this..
> fix paging headers when user doesnt provide rql

- src/Graviton/GeneratorBundle/Command/GenerateBundleCommand.php
- src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php
in wrapper context, there are more complex dependencies for regeneration stuff
here we change
* turn off debug mode in everything we start (makes things quicker) and compilerpasses don't run every single time
* don't purge BundleBundle, create a realtime one containing all existing bundles
* make sure the GenerateBundle job deletes the bundle directory before it generates the new (we cannot delete it in GenerateDynamicBundleCommand as the current cache expects it to exist..
so this should better things, maybe there are more edge cases that need more fixes..
> fix generator issues

- src/Graviton/FileBundle/Manager/FileManager.php
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
Based on EVO-5984, added the functionality. Posted files will now have custom hash if so is sent.
> EVO-8294 On posting a file, there should be the option to set custom HASH.

- app/config/config_test.yml
- src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php
- src/Graviton/RabbitMqBundle/Producer/Dummy.php
- src/Graviton/RabbitMqBundle/Producer/DummyChannel.php
- src/Graviton/RabbitMqBundle/Producer/JobProducer.php
- src/Graviton/RabbitMqBundle/Resources/config/services.xml
- src/Graviton/RabbitMqBundle/Tests/Controller/EventStatusControllerTest.php
- src/Graviton/RabbitMqBundle/Tests/Listener/EventStatusLinkResponseListenerTest.php
- src/Graviton/RestBundle/Controller/RestController.php
- src/Graviton/SecurityBundle/Service/SecurityUtils.php
Added Test for class EventStatusLinkResponseListener, no mock.
Changes storage token to use our SecurityUtils.
Created a AMQP dummy channel class so no events are put on queue but still able to see and match output.
> AMQP listener update with SecurityUtility and Test

- src/Graviton/I18nBundle/Document/Translatable.php
- src/Graviton/I18nBundle/Migrations/MongoDB/Version20161122111410.php
- src/Graviton/I18nBundle/Resources/config/doctrine/Translatable.mongodb.xml
- src/Graviton/I18nBundle/Tests/Controller/TranslatableControllerTest.php
Due to long original translation we need to remove the index original and update how id is generated
> Language Translatable ID to be sha1 encoded to avoid index overflow.

- src/Graviton/FileBundle/Controller/FileController.php
- src/Graviton/FileBundle/Manager/FileManager.php
On put requests, file metadata creationDate could be overwritten. This should not be possible.
We could define service as read-only field but we need to keep back-compatibility until workers and clients are updated.
> File create date shall be kept.

- composer.json
- composer.lock
- src/Graviton/I18nBundle/Listener/I18nSerializationListener.php
Upgrading serialiser from 1.1.0 to 1.4.2. Version 1.3 turned to not return expected key results.
Minor update in i18n listener to use new key value check.
setData, without the hasData can be used. Reviewer , please consider.
As reported in issue we need this feature to be in development environment for a while. Could give un-expected results in big serialised object that are not fully covered in test cases
> EVO-8951 Update Serialiser JMS/serializer to v1.4.2

- src/Graviton/FileBundle/Controller/FileController.php
request->get(metadata) was empty on multipart/mixed requests, moved the handler to be executed before to set the request
> File upload with POST multipart/mixed is not accepted straight by sf2

- composer.json
- composer.lock
- src/Graviton/I18nBundle/Listener/I18nSerializationListener.php
Changes of Serialiser gave issues in checklist serialisation: EVO-9238
"modules": {
"common": { ... },
"financing": { ... },
...
}
was rendered as
"modules": [
{ ... },
{ ... },
...
]
> Revert serialiser to v1.1.0

- src/Graviton/SecurityBundle/Authentication/SecurityAuthenticator.php
- src/Graviton/SecurityBundle/Authentication/Strategies/SameSubnetStrategy.php
Our firewall is sending x-auth but is not matching our field and still it stop checking for the cookie information. Here we continue to check cookie field data.
> Auth headers should not have empty username.

- app/config/parameters.yml.dist
- composer.json
- composer.lock
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentFieldNamesCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/DocumentMapCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/ExtRefFieldsCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/ReadOnlyFieldsCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/RecordOriginExceptionFieldsCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/RqlFieldsCompilerPass.php
- src/Graviton/DocumentBundle/DependencyInjection/Compiler/TranslatableFieldsCompilerPass.php
- src/Graviton/DocumentBundle/GravitonDocumentBundle.php
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/DocumentFieldNamesCompilerPassTest.php
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/ExtRefFieldsCompilerPassTest.php
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/RqlFieldsCompilerPassTest.php
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/TranslatableFieldsCompilerPassTest.php
- src/Graviton/DocumentBundle/Tests/Service/ExtReferenceConverterTest.php
- src/Graviton/GeneratorBundle/Command/GenerateDynamicBundleCommand.php
- src/Graviton/GeneratorBundle/DependencyInjection/Compiler/GeneratorHashCompilerPass.php
- src/Graviton/GeneratorBundle/GravitonGeneratorBundle.php
- src/Graviton/GeneratorBundle/Tests/Command/GenerateBundleCommandTest.php
- src/Graviton/I18nBundle/DependencyInjection/Compiler/ReplaceTranslatorCompilerPass.php
- src/Graviton/I18nBundle/GravitonI18nBundle.php
- src/Graviton/I18nBundle/Tests/Controller/ExternalTranslationDomainControllerTest.php
- src/Graviton/RabbitMqBundle/Listener/EventStatusLinkResponseListener.php
- src/Graviton/RestBundle/Listener/PagingLinkResponseListener.php
- src/Graviton/SwaggerBundle/Command/SwaggerGenerateCommand.php
- web/app.php
here we try to update to symfony 3.2 - looks quite good
What this PR changes
* Update all symfony deps to 3.2.* series
* Makes changes where necessary caused by the Symfony update
* Add ability to configure the "GravitonDyn" location via parameters.yml.. if it is not configured, it will behave as before
* swagger.json generation is smarter - it will hash all generated artifacts and decide if it needs to be regenerated or not.
> update to symfony 3.2

- src/Graviton/CoreBundle/Tests/Services/ReadOnlyFieldTest.php
- src/Graviton/SchemaBundle/Constraint/ReadOnlyFieldConstraint.php
Error happens if a field in a stored DB object is readonly, then the assessor will attempt to get that value but db object do not have it.
NoSuchPropertyException is thrown in: Symfony/Component/PropertyAccess/PropertyAccessor::readProperty
Can be tested on any post or put without the later readOnly field. Then do a put on that record and error of attempt to get property of stdClass failure.
> Bug fix for comparison object stored in db.

- app/config/config.yml
this seems to largely mitigate the problems we have (again) with disconnecting mongo connections
> higher retry connect for problems under php7.1 with the newest mongodb driver

- src/Graviton/GeneratorBundle/Command/GenerateBuildIndexesCommand.php
- src/Graviton/GeneratorBundle/Resources/skeleton/document/Document.mongodb.xml.twig
- src/Graviton/GeneratorBundle/Tests/Command/GenerateBuildIndexesCommandTest.php
- src/Graviton/RestBundle/Model/DocumentModel.php
We use this approach in order to create a temporary index so that the weighted index can be created later via: graviton:generate:build-indexes
> MongoDB 3.4 have slightly different index requirements versus 3.2

- src/Graviton/FileBundle/Manager/FileManager.php
- src/Graviton/FileBundle/Tests/Controller/FileControllerTest.php
Some clients when reading longer than 64 char hash strings they failed. So we do now limit this silently. 
EVO-10275
> File hash should not allow longer than 64 chars string, hash 256

- src/Graviton/CoreBundle/Resources/definition/Config.json
As part of a clean up in EVO-7820 we remove some fields from the service.
As fields with empty values are not displayed we just set those to not required and update initial data. 
We keep KEY index if field should be used for group query to make it back-compatible
> Set CoreConfig service fields to un-required.

- composer.lock
- src/Graviton/CoreBundle/Tests/Controller/PrimitiveArrayControllerTest.php
- src/Graviton/DocumentBundle/Entity/Hash.php
- src/Graviton/DocumentBundle/Serializer/Handler/HashHandler.php
We have in a few places fields that are allowed to store any kind of object data. 
If we accept a {} as empty this should then be returned as {}, but the serielizer will render this element as [] causing an error. Therefor we clean up the empty elements.
> Elements of a Empty free object if empty should not be returned.

- src/Graviton/CoreBundle/Resources/definition/Config.json
This reverts commit 9a1d85a91fc258b10aa5d78a9e4b4d65d27fce6c.
> Revert "Set CoreConfig service fields to un-required."

- .travis.yml
- src/Graviton/GeneratorBundle/Generator/DynamicBundleBundleGenerator.php
- src/Graviton/SchemaBundle/Document/Schema.php
- src/Graviton/SchemaBundle/SchemaUtils.php
This is part of clean-up process for cleaner response.
Schema response update.
Embedded object do not need the ID field unless it's required by definition. 
Our /schema/ {route} /collection was returning ID field due to serialised object Schema class so we do now hide this but allow it still in validation if post/put ( Back-compatibility needed yet due to some Admins/Clients are still sending this value )
Added KEY sort bundle names to have same output in GravitonDyn load bundles array.
> Feature/evo 7836 schema hide embedded ID

- src/Graviton/RabbitMqBundle/Resources/definition/EventStatus.json
Due to pooling status updates via admin we need to index the minimal fields to speed up response.
> Set indexes for Event Status api

- src/Graviton/ProxyBundle/Resources/config/routing.yml
- src/Graviton/ProxyBundle/Resources/config/services.yml
there were some errors for the sq routing after the YAML migration, this fixes the SQ routing as well as the 
```
"message": "Attempted to load class \"Proxy roxy\" from the global namespace.\nDid you forget a \"use\" statement?"
```
error
> EVO-10759: fix sq routing

- src/Graviton/RestBundle/Resources/config/services.yml
This header needs to be there to allow PreFlight.
> In testing environment we use BasicAuth

- .travis.yml
- app/config/config_test.yml
- composer.json
- composer.lock
- src/Graviton/CoreBundle/Command/GenerateVersionsCommand.php
- src/Graviton/CoreBundle/Resources/config/services.yml
- src/Graviton/CoreBundle/Tests/Command/GenerateVersionsCommandTest.php
- src/Graviton/GeneratorBundle/Definition/Loader/Strategy/DirStrategy.php
- src/Graviton/GeneratorBundle/Tests/Definition/Loader/Strategy/DirStrategyTest.php
- src/Graviton/GeneratorBundle/Tests/Definition/Loader/Strategy/ScanStrategyTest.php
Travis is currently red on develop and master for PHP 7.*, this fixes that.
Also updates all deps except Symfony
> Fix travis build & update deps (except Symfony)

- src/Graviton/CoreBundle/Tests/Controller/ShowcaseControllerTest.php
- src/Graviton/SchemaBundle/SchemaUtils.php
make sure we expose "id" property for embedded objects, but NOT for extref objects.. 
add test to assert the behavior
> EVO-11664 - embed id in schema

- src/Graviton/DocumentBundle/DependencyInjection/Compiler/SolrDefinitionCompilerPass.php
- src/Graviton/DocumentBundle/Service/SolrQuery.php
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/Resources/schema/A.json
- src/Graviton/DocumentBundle/Tests/DependencyInjection/CompilerPass/SolrDefinitionCompilerPassTest.php
- src/Graviton/DocumentBundle/Tests/Listener/RqlSearchNodeListenerTest.php
- src/Graviton/DocumentBundle/Tests/Service/SolrQueryTest.php
there is strange behavior how edismax parses our query sometimes, using AND/NOT keywords as text strings in the generated search
> change solr operators

- composer.lock
- src/Graviton/RestBundle/Listener/RestrictionListener.php
- src/Graviton/RestBundle/Tests/Controller/RestrictionListenerTest.php
If no restriction header is sent, we are fully admin now and can modify all tenant records. Existing tenant gets persisted to the new record
> allow null tenant modification
